---
title: "BEE 4750: Environmental Systems Analysis"
---

Environmental processes can have complicated dynamics and conflicting objectives. These dynamics can complicate analyses and decision-making which focus on a single component of the system, such as an individual pollution source. In this course, we will adopt a systems approach to environmental quality modeling and management, including applications in air and water pollution control and solid waste management. In particular, we will:

* learn how to define systems and their boundaries;
* simulate system dynamics using computer models;
* formulate and solve linear and nonlinear optimization problems;
* analyze and assess risk after introducing uncertainty;
* make decisions under uncertainty with stochastic and dynamic programming; and
* explore trade-offs across competing objectives.

::: {.callout-note}
## Julia

This course will use the [Julia](https://julialang.org) programming language. No prior knowledge of Julia is required.
:::
