---
title: Final Project
tbl-colwidths: [20, 5, 5, 5, 10]
---

## Overview

The final project gives you an opportunity to use and extend the methods we have learned in class to an environmental system of your choosing. More details will be provided over the semester. We will discuss each component in class as well as providing relevant information on this page.

## Overall Instructions

- Students in 4750 should work in groups of 2-3, while students in 5750 must work alone.

## Schedule

Milestones which are only for BEE 5750 or 4750 students are in *italics*.

| Milestone | Points | Instructions | Rubric | Due Date |
|:---------:|:------------:|:-------:|:-----------|:---------:|
| Proposal | 10 | [{{< fa sharp pen-field >}}](project/proposal.qmd) |  | Fri, Sep 29 |
| Proposal Peer Review | 10 | [{{< fa sharp pen-field >}}](project/proposal-review.qmd) | [{{< fa sharp list-check >}}](rubrics/proposal-review.qmd) | Mon, Oct 2 |
| Regulations Report | 20 | [{{< fa sharp pen-field >}}](project/regulation.qmd)  | [{{< fa sharp list-check >}}](rubrics/regulation.qmd) | Fri, Oct 27 |
| Project Update | 10 | | | Fri, Nov 10 |
| Presentation | 15 | | | Fri, Dec 4 |
| Presentation Peer Review | 5 | | | Fri, Dec 15 |
| Poster | 20  | | | Fri, Dec 15 |
| *Literature Review* (5750 only) | 10 | | | Fri, Dec 15 |
| *Team Evaluations* (4750 only) | 10 | | | Fri, Dec 15 |

## Scope and Topics

The project can be on any environmental system of interest, so long as the approaches from class are being extended in some way. This can involve applying new methods (*e.g.* multi-objective optimzation, more advanced uncertainty analysis, lifecycle analysis) to systems studied from class, or applying class or new methods to other systems. 

Some project topics from previous semesters include:

- Battery lifecycle analysis for residential storage;
- Hydropower production from Ithaca-area streams;
- Traffic regulation to comply with air-quality standards;
- Wastewater treatment design;
- Geothermal energy lifecycle analysis;
- Multi-objective optimization for water management;
- Energy storage on Cornell's campus;
- Flight schedule optimization;
- Milk alternatives lifecycle analysis;
- Hydrogen fuel cell lifecycle analysis.