---
title: Resources
---

## General

* [UDM14](https://udm14.com/): Google search without AI distortion (or you could use the instructions to make [&udm=14 the default](https://tedium.co/2024/05/17/google-web-search-make-default/)).

## Julia

* [Setting up VS Code and Julia (Youtube)](https://www.youtube.com/watch?v=KesuPOlBB_o)
* [Julia Documentation](https://docs.julialang.org/en/v1/)
* [JuliaAcademy](https://juliaacademy.com/courses): Check out the "Introduction to Julia (for programmers)" or "Julia Programming for Nervous Beginners" courses
* [QuantEcon MATLAB-Python-Julia cheatsheet](https://cheatsheets.quantecon.org/)
* [FastTrack to Julia cheatsheet](https://juliadocs.github.io/Julia-Cheat-Sheet/)
* [Plotting cheatsheet](https://github.com/sswatson/cheatsheets/blob/master/plotsjl-cheatsheet.pdf)
* [Introduction to Computational Thinking](https://computationalthinking.mit.edu/Spring21/): a great Julia based course at MIT!
* [Comprehensive Julia Tutorials](https://www.youtube.com/playlist?list=PLCXbkShHt01seTlnlVg6O7f6jKGTguFi7): YouTube playlist covering a variety of Julia topics, starting with an introduciton to the language.
* [Introduction to `JuMP`](https://jump.dev/JuMP.jl/stable/tutorials/getting_started/getting_started_with_JuMP/)


## GitHub

* [Git Basics](https://www.theodinproject.com/lessons/foundations-git-basics) from The Odin Project.
* [Learn Git Branching](https://learngitbranching.js.org/): An interactive, visual tutorial to how git works.
* [Version Control](https://missing.csail.mit.edu/2020/version-control/) from MIT's "CS: Your Missing Semester" course.
* [Git and GitHub for Poets](https://www.youtube.com/playlist?list=PLRqwX-V7Uu6ZF9C0YMKuns9sLDzK6zoiV): YouTube playlist covering the basics of git and GitHub.


## Markdown

* [Markdown Cheatsheet](https://www.markdownguide.org/cheat-sheet/)
* [GitHub Markdown Cheatsheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) (note that not all of these commands may work in Jupyter notebooks, as GitHub Markdown is an expanded syntax
* [LaTeX Cheatsheet](https://ctan.math.washington.edu/tex-archive/info/undergradmath/undergradmath.pdf)

## Optimization


* [Decision Modeling e-Book](https://linney.mun.ca/pages/view.php?ref=36808): this uses Excel Solver, but may have useful information on problem setup and optimization methods.
* [Algorithms for Decision-Making](https://algorithmsbook.com/): open-access book based on Julia with more depth on optimization and decision-making algorithms than we will cover in this class.