---
format:
  html:
    toc-depth: 3
    title: Syllabus
  pdf:
    documentclass: article
    geometry:
      - margin=1in  
    include-in-header:
      text: |
        \renewcommand\toprule[2]\relax
        \renewcommand\bottomrule[2]\relax
    filters:
      - _assets/filters/columns-to-tables.lua
    title: "{{< var course.number >}} ({{< var course.title >}}) Syllabus"
    subtitle: "{{< var course.semester >}}"
  docx:
    toc: true
    toc-depth: 2
    number-sections: false
---

```{julia}
#| echo: false
#| output: false

import Pkg
Pkg.activate(".")
Pkg.instantiate()

using Dates
using DataFrames
using PrettyTables
```

## Course Overview

This is a 3 credit course which is required for the Environmental Engineering major, and can only be taken for a letter grade.

## Course Information
:::: {.columns .course-details}

::: {.column width="30%"}
### Instructor

- {{< fa sharp user title="Name" >}} [[{{< var instructor.name_no_title >}}]({{< var instructor.url >}})]{.ms-1}
- {{< fa sharp envelope title="Email" >}} [[{{< var instructor.email >}}](mailto:{{< var instructor.email >}})]{.ms-1}
- {{< fa sharp building title="Office" >}} [{{< var instructor.office >}}]{.ms-2}
:::

::: {.column width="30%"}
### TA

- {{< fa sharp user title="Name" >}} [Gabriela Ackermann Logan]{.ms-1}
- {{< fa sharp envelope title="Email" >}} [ga345@cornell.edu]{.ms-1}
- {{< fa sharp building title="Office" >}} [319 Riley-Robb]{.ms-2}
::::

::: {.column width="30%"}
### Meetings

- {{< fa sharp calendar title="Class Days" >}} {{< var course.days >}}
- {{< fa sharp clock title="Class Time" >}} {{< var course.time >}}
- {{< fa sharp university title="Class Location" >}} {{< var course.location >}}

:::


::::

### Course Description

Environmental systems involve multiple interacting processes, uncertainties, and potentially conflicting objectives. These dynamics can complicate analyses which focus on a single component of the system, such as an individual pollution source, or a single outcome of interest. In this course, we will adopt a systems approach to environmental quality modeling and management, including applications in air and water pollution control and solid waste management. In particular, we will:

* define systems and their boundaries;
* simulate system dynamics using computer models;
* formulate and solve decision problems for systems management;
* analyze and assess risk;
* make decisions under uncertainty; and
* explore trade-offs across competing objectives. 

## Learning Objectives

At the end of this class, students will:

1. Construct mathematical models of environmental systems;
2. Use systems models to simulate dynamics and outcomes;
3. Analyze environmental system risk and vulnerabilities.
4. Determine strategies for managing systems using optimization;
5. Identify the  trade-offs  that  result  from  competing  objectives  in  environmental  decision -making; 
6. Evaluate modeled outcomes with respect to model assumptions and limits.

## Prerequisites & Preparation

The following courses/material would be ideal preparation:

- Environmental Processes (BEE 2510 or BEE 2600)
- Engineering Computation (ENGRD/CEE 3200)
- One course in probability or statistics (ENGRD 2700, CEE 3040, or equivalent) 

In the absence of one or more these prerequisites, you can seek the permission of instructor.

::: {.callout-tip}
## What If My Programming or Stats Skills Are Rusty?

If your programming or statistics skills are a little rusty, don't worry! We will review concepts and build skills as needed.
:::

## Topics

* Introduction to environmental systems, 
* Modeling system dynamics
* Multiple objectives and trade-offs
* Uncertainty and risk (Monte Carlo analysis)
* Dissolved oxygen in streams and rivers; waste load allocation (system simulation)
* Modeling of watersheds & lakes (defining objectives, constraints)
* Modeling for air pollution control (model linearization; linear programming)
* Location of waste disposal facilities (integer linear programming)
* Robustness of solutions and sensitivity analysis


## Course Philosophy and Expectations

The goal of our course is to help you gain competancy and knowledge in the area of environmental systems analysis. This involves a dual responsibility on the part of the instructor and the student. As the instructor, my responsibility is to provide you with a structure and opportunity to learn. To this end, I will commit to:

* provide organized and focused lectures, in-class activities, and assignments;
* encourage students to regularly evaluate and provide feedback on the course;
* manage the classroom atmosphere to promote learning;
* schedule sufficient out-of-class contact opportunities, such as office hours;
* allow adequate time for assignment completion;
* make lecture materials, class policies, activities, and assignments accessible to students. 

Students are encouraged to discuss any concerns with me during office hours or through a course communications channel.

Students can optimize their performance in the course by:

- attending all lectures;
- doing any required preparatory work before class; 
- actively participating in online and in-class discussions;
- beginning assignments and other work early;
- and attending office hours as needed. 

## Community

### Diversity and Inclusion

Our goal in this class is to foster an inclusive learning environment and make everyone feel comfortable in the classroom, regardless of social identity, background, and specific learning needs. As engineers, our work touches on many critical aspects of society, and questions of inclusion and social justice cannot be separated from considerations of systems analysis, objective selection, risk analysis, and trade-offs. 

In all communications and interactions with each other, members of this class community (students and instructors) are expected to be respectful and inclusive. In this spirit, we ask all participants to:

* share their experiences, values, and beliefs;
* be open to and respectful of the views of others; and
* value each other's opinions and communicate in a respectful manner.

Please let me know if you feel any aspect(s) of class could be made more inclusive. Please also share any preferred name(s) and/or your pronouns with me if you wish: I use he/him/his, and you can refer to me either as Vivek or Prof. Srikrishnan.

::: {.callout-important}
## Please, Be Excellent To Teach Other

We all make mistakes in our communications with one another, both when speaking and listening. Be mindful of how spoken or written language might be misunderstood, and be aware that, for a variety of reasons, how others perceive your words and actions may not be exactly how you intended them. At the same time, it is also essential that we be respectful and interpret each other's comments and actions in good faith. 
:::


### Student Accomodations

Let me know if you have any access barriers in this course, whether they relate to course materials, assignments, or communications. If any special accomodations would help you navigate any barriers and improve your chances of success, please exercise your right to those accomodations and reach out to me as early as possible with your [Student Disability Services](https://sds.cornell.edu/) (SDS) accomodation letter. This will ensure that we have enough time to make appropriate arrangements.

If you need more immediate accomodations, but do not yet have a letter, please let me know and then follow up with SDS.

### Course Communications

Most course communications will occur via [Ed Discussion](https://edstem.org). Public Ed posts are generally preferred to private posts or emails, as other students can benefit from the discussions. If you would like to discuss something privately, please do reach out through email or a private Ed post (which will only be viewable by you and the course staff).

Announcements will be made on the course website and in Ed. Emergency announcements will also be made on Canvas.

::: {.callout-important}
## Ed Tips

- If you wait until the day an assignment is due (or even late the previous night) to ask a question on Ed, there is a strong chance that I will not see your post prior to the deadline. 
- But if you see unanswered questions and you have some insight, please answer! This class will work best when we all work together as a community.
:::


### Mental Health Resources

We all have to take care of our mental health, just as we would our physical health. As a student, you may experience a range of issues which can negatively impact your mental health. Please do not ignore any of these stressors, or feel like you have to navigate these challenges alone! You are part of a community of students, faculty, and staff, who have a responsibility to look for one another's well-being. If you are struggling with managing your mental health, or if you believe a classmate may be struggling, please reach out to the course instructor, the TA, or, for broader support, please take advantage of [Cornell's mental health resources](https://mentalhealth.cornell.edu/).

::: {.callout-important}
## Mental Health And This Class

I am not a trained counselor, but I am here to support you in whatever capacity we can. You should never feel that you need to push yourself past your limits to complete any assignment for this class or any other. If we need to make modifications to the course or assignment schedule, you can certainly reach out to me, and all relevant discussions will be kept strictly confidential. 

:::


## Course Policies

### Attendance

Attendance is not *required*, but in general, students who attend class regularly will do better and get more out of the class than students who do not. Your class participation grade will reflect both the quantity and quality of your participation, only some of which can occur asynchronously. I will put as many course materials, such as lecture notes and announcements, as possible online, but viewing materials online is not the same as active participation and engagement. Life happens, of course, and this may lead you to miss class. Let me know if you need any appropriate arrangements ahead of time. 

::: {.callout-important}
## What If I'm Sick?

Please stay home if you're feeling sick! This is beneficial for both for your own recovery and the health and safety of your classmates. We will also make any necessary arrangements for you to stay on top of the class material and if whatever is going on will negatively impact your grade, for example by causing you to be unable to submit an assignment on time.

:::

### Mask Policies

**Masks are encouraged but not required in the classroom**, per [university policy](https://covid.cornell.edu/updates/20220727-students-fall-semester.cfm). However, the University *strongly encourages* compliance with requests to mask from students, faculty, and staff who are concerned about the risk of infection. Please be respectful of these concerns and requests if you cannot wear a mask.

### Academic Integrity

::: {.callout-important}
**TL;DR**: Don't cheat, copy, or plagiarize!
:::

This class is designed to encourage collaboration, and students are encouraged to discuss their work with other students. However, I expect students to abide by the [Cornell University Code of Academic Integrity](http://theuniversityfaculty.cornell.edu/academic-integrity/) in all aspects of this class.  **All work submitted must represent the students' own work and understanding**, whether individually or as a group (depending on the particulars of the assignment). This includes analyses,  code,  software  runs,  and  reports. Engineering as a profession relies upon the honesty and integrity of its practitioners (see *e.g.* the [American Society for Civil Engineers' Code of Ethics](https://www.asce.org/-/media/asce-images-and-files/career-and-growth/ethics/documents/asce-code-ethics.pdf)).

### External Resources

The collaborative environment in this class **should not be viewed as an invitation for plagiarism**. Plagiarism occurs when a writer intentionally misrepresents another's words or ideas (including code!) as their own without acknowledging the source.  **All** external resources which are consulted while working on an assignment should be referenced, including other students and faculty with whom the assignment is discussed. You will never be penalized for consulting an external source for help and referencing it, but plagiarism will result in a zero for that assignment as well as the potential for your case to be passed on for additional disciplinary action.

### AI/ML Resource Policy

As noted, all work submitted for a grade in this course must reflect your own understanding. The use and consulation of AI/ML tools, such as ChatGPT or similar, must be pre-approved and clearly referenced. If approved, you must:

- reference the URL of the service you are using, including the specific date you accessed it;
- provide the exact query or queries used to interact with the tool; and
- report the exact response received.

**Failure to attain prior approval or fully reference the interaction, as described above, will be treated as plagiarism and referred to the University accordingly.**

### Late Work Policy

In general, late work will be subjected to a 10% penalty per day, *which can accumulate to 100% of the total grade*. However, sometimes things come up in life. Please reach out *ahead of time* if you have extenuating circumstances (including University-approved absences or illnesses) which would make it difficult for you to submit your work on time. Work which would be late for appropriate reasons will be given extensions and the late penalty will be waived.

## Assessments

### Lab Notebooks: 20%

Some classes will involve hands-on exercises (which we will call "labs") which will give you guided practice applying the concepts and methods from class. These classes will be announced on [the course website](https://viveks.me/environmental-systems-analysis) ahead of time so anyone who is able can bring a laptop to class, and notebooks will be provided on GitHub. These labs can be done in groups; if you cannot bring a laptop to class for whatever reason, you will be able to (and are encouraged to) work with other students, though you must turn in your own notebook for grading.

Some details on lab logistics:

- Some of the labs may some time outside of class, but they will not be as intensive as a homework assignment. 
- You will be required to submit a PDF of your completed notebook to Gradescope by 9:00pm by the due date (which will be approximately one week) after the lab session. Tag the answers to each question: points will be deducted if this is not done.
- While your lowest lab grade will not be dropped, late penalties will be waived for appropriate reasons discussed with the instructor (ideally ahead of time when circumstances allow).
- Rubrics will be provided for lab grading as part of the lab assignments.

### Homework Assignments: 40%

Approximately 5-6 homework assignments will be assigned throughout the semester; the specifics depend on how quickly we move through the material. You will typically have 10 days to 2 weeks to work on Students are encouraged to collaborate and learn from each other on homework assignments, but each student must submit their own solutions reflecting their understanding of the material. Consulting and referencing external resources and your peers is encouraged (engineering is a collaborative discipline!), but  plagiarism is a violation of academic integrity.

Some notes on assignment and grading logistics:

  * Homework assignments will be distributed using GitHub Classroom. Students should make sure they update their GitHub repositories as they work on the assignments; this helps with answering questions and gives you a backstop in case something goes wrong and you can't submit your assignment on time.
  * Homeworks are due by 9:00pm Eastern Time on the designed due date. Your assignment notebook (which include your writeup and codes) should be submitted to Gradescope as a PDF with the answers to each question tagged (a failure to do this will result in deductions). 
  * Rubrics will be provided for the homeworks as part of the assignments.
  * Your lowest homework grade will be dropped. We can discuss arrangements if multiple assignments will be missed for university-approved reasons, preferably ahead of time. 
  * Regrade requests for specific problems must be made within a week of the grading of that assignment. However, note that regrades can cut both ways: the TA can take away points as well!

### Final Term Project: 40%

This course will culminate with a term project with a topic selected from a suggested list (provided mid-semester). The goal of this project is to apply and extend the tools and approaches we will learn in class. While we encourage drawing on other classes or interests when developing and working on your project, **submitting work from another course or work which was completed prior to the course is not permitted**.

The term project will be completed in small groups (2-3 students) for students enrolled in BEE 4750 and individually for those in BEE 5750. The final deliverable for this project will be a poster summarizing the project and results. Ahead of that, you will submit the following:

- a proposal for feedback on the scope of your project; and
- a 2-3 page report on the status and history of a regulation of interest relevant to the system you are studying.

Rubrics will be provided for the components of the project.

::: {.content-visible unless-format="html"}
## Tentative Schedule

```{julia}
#| echo: false
#| output: false

start_date = Date(2023, 8, 21)
end_date = Date(2023, 12, 4)

# set vector of class dates (including holidays)
cdates = filter(d -> Dates.dayname(d) ∈ ["Monday", "Wednesday", "Friday"], Date(start_date):Day(1):Date(end_date));
# find weeks from first week of classes
cweeks = week.(cdates) .- (week(Date(start_date)) - 1);
# get days of the week
cdays = dayabbr.(cdates)

# set vector of class topics
topics = [ 
  "Class overview",
  "Intro to Julia and GitHub",
  "Lab 1: Julia Basics",
  "Defining System Boundaries",
  "Examples of Systems Dynamics",
  "Examples of Systems Dynamics cont'd",
  "Modeling Systems",
  "Simulating Systems with Models",
  "Simulation Example: Dissolved Oxygen",
  "Simulation Example: Dissolved Oxygen cont'd",
  "Lab 2: Systems Simulation",
  "Probability and Statistics Review",
  "Probability and Statistics Review cont'd",
  "Introduction to Monte Carlo",
  "Monte Carlo Error Analysis",
  "Lab 3: Monte Carlo",
  "Risk Analysis for Systems",
  "Systems Management Decisions",
  "Introduction to Optimization",
  "Introduction to Optimization, cont'd",
  "Guest Lecture on Researching Regulations",
  "Linear Programming",
  "Linear Programming cont'd",
  "Lab 4: Linear Programming with JuMP",
  "Emissions and Plume Models",
  "Plume Models cont'd",
  "Power Systems Modeling and Economic Dispatch",
  "Economic Dispatch cont'd",
  "Mixed-Integer Programming",
  "Unit Commitment",
  "Unit Commitment cont'd",
  "Network Models and Solid Waste Management",
  "Solid Waste Management cont'd",
  "Simulation-Optimization",
  "Lab 5: Simulation-Optimization", 
  "Robustness",
  "Sensitivity Analysis",
  "Sensitivity Analysis cont'd", 
  "Multiple Objectives and Trade-Offs",
  "Scenario Trees",
  "Decision-Making Under Uncertainty cont'd",
  "Value of Uncertainty"
]

holiday_dates = ["2024-09-04", "2024-10-09", "2024-11-22", "2024-11-24"];
holidays = DataFrame(Date=Dates.format.(Date.(holiday_dates), "mm-dd"), 
                    Holiday=["Labor Day", "Fall Break", "Thanksgiving Break", "Thanksgiving Break"]);

# add in holidays
ctopics = Vector{String}(undef, length(cdates)); # initialize array
cschedule = DataFrame(Date=Dates.format.(cdates, "mm-dd"), Day=cdays);
leftjoin!(cschedule, holidays, on=:Date);
rename!(cschedule, :Holiday => :Topic);
cschedule[ismissing.(cschedule.Topic), :Topic] = topics;


# number class meetings
class_nums = missings(Int, length(cdates))
class_nums[cschedule.Date .∉ [holidays.Date]] = collect(range(1, length=length(cdates) - nrow(holidays)))

# set headers
headers_idx = [1, 5, 11, 22, 42, 49]
headers = DataFrame([
  "" "" "Course Introduction";
  "" "" "Introduction to Systems Analysis";
  "" "" "Systems Simulation";
  "" "" "Optimization and Systems Management";
  "" "" "Examining Assumptions";
  "" "" "Decision-Making Under Uncertainty";
], ["Date", "Day", "Topic"])

for i = 1:length(headers_idx)
  insert!(cschedule, headers_idx[i], headers[i, :]; promote=true)
  insert!(class_nums, headers_idx[i], missing)
end

class_nums = coalesce.(class_nums, "")


```
:::

::: {.content-visible when-format="pdf"}

```{julia}
#| echo: false
#| output: asis

# highlight holidays
hl_smallfont = LatexHighlighter((data,i,j)->true, ["small"])
hl_hol = LatexHighlighter((data, i, j) -> data[i, :Date] ∈ holidays[:, :Date], ["emph", "small"])
hl_header = LatexHighlighter((data, i, j) -> i ∈ headers_idx, ["emph", "textbf", "small"])

pretty_table(cschedule, highlighters=(hl_header, hl_hol, hl_smallfont), 
  body_hlines = headers_idx[2:end] .- 1,
  nosubheader=true, backend=Val(:latex), tf=tf_latex_modern, formatters=ft_nomissing,
  row_names=class_nums, row_name_alignment=:r, row_name_column_title = "\\#", wrap_table=true, wrap_table_environment="center", table_type=:longtable,
  alignment = [:c, :c, :l])
```
:::

::: {.content-visible when-format="docx"}

```{julia}
#| echo: false
#| output: asis

using Latexify

bold_headers(x) = x in headers.Topic ? "***$x***" : x  
cschedule = bold_headers.(cschedule)
italicize_holidays(x) = x in unique(holidays.Holiday) ? "*$x*" : x
cschedule = italicize_holidays.(cschedule)
print(latexify(cschedule; env=:mdtable, latex=:false, adjustment=:l))
```
:::

