---
title: "Getting Started with Julia and GitHub"
subtitle: "Lecture 02"
author: "Vivek Srikrishnan"
course: "BEE 4750"
institution: "Cornell University"
date: "August 23, 2023"
format:
    revealjs:
        slide-number: c/t
        show-slide-number: all
        center-title-slide: true
        width: 1280
        height: 720
        transition: none
        toc: false
        toc-depth: 1
        toc-title: "Overview"
        history: false
        link-external-newwindow: true
        theme: ../sass/slides.scss
        footer: "[BEE 4750, Environmental Systems Analysis](https://viveks.me/environmental-systems-analysis)"
        template-partials:
            - title-slide.html
        menu:
            numbers: true
execute:
    freeze: auto
---

# Application Exercise 1

## Overview

Application exercises are short assignments meant to tie into the week's discussion. 

- These might be small coding exercises (for practice) or mini problems (think about a particular system for discussion).

- We will not normally work on these in class.

::: {.fragment .fade-in}
Today is an exception --- focus on getting acquainted with the basic workflow and toolkit.
:::

## Instructions

If you haven't already, go to the [instructions]({{< var course.url >}}/aes/ae01/ae01.html).

For this application exercise, the instructions will:

- walk you through installing git, Julia and VS Code;
- creating a GitHub account;
- cloning the repository;
- opening and editing the notebook;
- exporting to PDF for Gradescope.

## Tips

- Do not have to finish this in class, but please make sure to ask questions if you reach any sticking points.
- Must submit PDF by **Friday at 9:00pm**: turnaround is short this week, but there is little work for this one.
- If you have extra time, can get started on [Homework 1]({{< var course.url >}}/hw/hw01/hw01.html) (get the GitHub link from [Ed Discussion](https://us.edstem.org)).

# Upcoming Schedule

## Next Class

Work on Lab 1. 

- Preparation: 
    - Lab 1 link is available on Ed. Click it to accept the lab before class, and based on Wednesday.


