---
title: "Uncertainty and Monte Carlo"
subtitle: "Lab 02"
author: "Vivek Srikrishnan"
course: "BEE 4750"
institution: "Cornell University"
date: "September 18, 2023"
format:
    revealjs:
        slide-number: c/t
        show-slide-number: all
        center-title-slide: true
        width: 1280
        height: 720
        transition: none
        toc: true
        toc-depth: 1
        toc-title: "Overview"
        history: false
        link-external-newwindow: true
        theme: ../sass/slides.scss
        footer: "[BEE 4750, Environmental Systems Analysis](https://viveks.me/environmental-systems-analysis)"
        template-partials:
            - title-slide.html
        menu:
            numbers: true
        html-math-method: mathjax      
        include-in-header: mathjax-config.html
        date-format: long
execute:
    freeze: auto
---


# Lab 2 Instructions

## Monte Carlo for ECS Uncertainty

Your task in the lab: analyze two different games of "chance" (one is, one sort of is). 

Lab is due on 9/22 by 9pm.

## Reminder About The Rubric

For full points, make sure to check rubric (available on the Labs page of the website; Homework is similar) before finalizing submission. If unsure if something might be penalized, please ask on Ed or in class. In general, points will be taken off for:

* Missing units;
* Plots: Unlabeled axes/missing legends if needed;
* Lack of proper precision when reporting values.

# Upcoming Schedule

## Next Classes

**Wednesday**: Monte Carlo wrap-up

**Friday**: Uncertainty and Simple Climate Models

**Next Week**: Prescriptive Modeling and Optimization

## Assessments

**Friday**: Homework 2 and Lab 2 both due.