---
title: Literature Review Instructions
format:
    html: default
    pdf:
        documentclass: article
        geometry:
            - margin=1in  
        include-in-header:
            text: |
                \renewcommand\toprule[2]\relax
                \renewcommand\bottomrule[2]\relax
        filters:
            - ../_assets/filters/columns-to-tables.lua
---

## Overview

The literature review is intended for students in BEE 5750 to synthesize 2-3 papers that they have read which are relevant to the system for their project.

## Instructions

- Your review should be no more than 2 pages, ***not including references***.
- Your review should *synthesize*, not just report on, the papers you have selected. This includes:
    - What are the key question(s) of the studies, and how are they related?
    - What were the key findings?
    - How appropriate were the methods in addressing the questions, and are the findings well supported by the analysis?
    - What are your takeaways from the papers, and what opportunities to expand or improve exist?
- The review should have the following format:
    - 1/2 inch margins on each side;
    - 12 point Calibri font;
    - 1.5x line spacing.
- Submit a PDF of the review to Gradescope by 9:00 PM on the due date. 