---
title: Proposal Peer Review Instructions
format:
    html: default
    pdf:
        documentclass: article
        geometry:
            - margin=1in  
        include-in-header:
            text: |
                \renewcommand\toprule[2]\relax
                \renewcommand\bottomrule[2]\relax
        filters:
            - ../_assets/filters/columns-to-tables.lua
---

## Overview

The proposal peer review is intended to serve two purposes, one for the reviewer and one for the writer of the proposal.

1. One of the best ways to improve as a writer is to read what others write. You may see aspects of other proposals that you either wish that you had included or you may see some that you want to make sure to avoid in the future. As you move forward in your career, you may write and read these kinds of documents.
2. As a writer, it's always helpful to get others' eyes on your writing. This feedback will be useful as you move forward with your project and it takes more concrete shape.

You will each review two proposals from other groups. The review process should be short.

## Instructions

- You will be prompted to submit an anonymized version of your proposal to Canvas.
- Prior to class on the peer review date, you will be assigned two proposals to review anonymously. 
- Read each proposal carefully and with a view towards the rubric below. You will choose a rating for each rubric item.
- Write some comments synthesizing the positive and negative aspects of the proposal across the rubric entries.
- Submit your reviews by 9pm on the peer review date.
- Your reviews have no bearing on grades, so keep them constructive. The goal is to help improve your final projects and those of your classmates.
- You will be graded on completing the reviews (90%) and reading your received reviews (10%).

## Rubric

| **Component** | Needs A Lot Of Improvement | Needs Some Improvement | Fine As Is | Good |
|:-------------:|:------------|:------------|:------------|:-------------|
| **Problem Description** | No problem description or goal provided. | Problem description or goals provided, but unclear. | Clear problem description or goals provided, but problem may not be well motivated. | Clear problem description or goals provided and well motivated as an interesting problem. |
| **System Overview** | No description of the system for the analysis or description missing key details such as assumptions about included components and processes or metrics. | Description of system provided and appears complete but is unclear. | Description is clear and includes necessary information, but details are vague. | Description is clear, includes all information, and is detailed. |
| **Alignment of System and Problem** | Unclear how system is relevant to the problem of interest. | System description is not well aligned with the problem description (e.g. there is a mismatch between the goals and which processes are included and how). | System and problem appear aligned but some lack of clarity in justifying why certain components were or weren't included. | System and problem are well aligned and this is clear from the descriptions. |
| **Experimental Design** | No or unclear details about proposed design included (metrics, uncertainties, data). | Proposed design described but may require more details to be actionable. | Proposed design may be slightly vague, but can get a complete picture of what the group is trying to do. | Proposed design is clear and actionable. |
| **References** | References not included. | References included, but there are several places that should be referenced but are not. | References included and appropriate. | Proposal is thoroughly  and clearly referenced. |
