---
title: Regulations Report Instructions
format:
    html: default
    pdf:
        documentclass: article
        geometry:
            - margin=1in  
        include-in-header:
            text: |
                \renewcommand\toprule[2]\relax
                \renewcommand\bottomrule[2]\relax
        filters:
            - ../_assets/filters/columns-to-tables.lua
---

## Overview

The goal of the regulations report is to identify the regulatory context for the system you are analyzing for your project. You will focus on one regulation which is applicable to your selected problem. An important component of the report is the identification of appropriate sources for research.

## Instructions

- Your report should be no more than 3 pages, ***not including figures or references***.
- You should include the following information in your report (written as a narrative, rather than as a list):
    - The regulation you are researching;
    - The problem the regulation was intended to solve;
    - The history of the regulation's proposal, amendments, and current state;
    - At least three specific instances of proposed rule-making, revision, or public comment in the regulatory process that applied to your regulation^[If you cannot find three instances, document your search process and those you were able to find];
    - How you plan to incorporate your regulation into your systems model;
    - References for any sources consulted, including academic literature, websites, and news articles.
- Include the name(s) of the project team at the top of the PDF.
- The report should have the following format:
    - 1/2 inch margins on each side;
    - 12 point Calibri font;
    - 1.5x line spacing.
- Submit a PDF of the proposal to Gradescope by 9:00 PM on the due date. 