---
title: Project Update Instructions
format:
    html: default
    pdf:
        documentclass: article
        geometry:
            - margin=1in  
        include-in-header:
            text: |
                \renewcommand\toprule[2]\relax
                \renewcommand\bottomrule[2]\relax
        filters:
            - ../_assets/filters/columns-to-tables.lua
---

## Overview

For this update, you should provide a clear statement of the question and goal(s) of your project, your model specification, as well as what data you are using to support your analysis. 

While minor changes can be made to your project at this point (tweaking the project, using a slightly different approach), you should commit to the big picture scope (system of interest, overarching question).

## Instructions

You should include the following information in your update:

- A brief (no more than 1/2 page) overview of your system and the background for your project;
- The question you are addressing for your project (this should take no more than 1/2 page);
- The specific aims of your project (what concrete steps you intend to take to address the question; make this clear, ideally use bulleted lists to separate out different steps/tasks);
- Your model formulation: include equations and diagrams as needed to make it clear how you are setting up your model;
- Justification of your modeling choices with respect to the question and aims: are the choices you are making helping you address the question you posed, and are you making assumptions that might influence the results (and if so, make those clear); this should be no more than 2 pages;
- Identification of data sources you will use to conduct your analysis, as well as how you intend to use the data in your aims.
- References for all sources consulted, including any identified datasets (format of the references is not critical, but use a standard style); **make sure to cite references as appropriate within the text**;
- Include the name(s) of the project team at the top of the PDF.
- The update should have the following format:
    - 1/2 inch margins on each side;
    - 12 point Calibri font;
    - 1.5x line spacing.
- Submit a PDF of the update to Gradescope by 9:00 PM on the due date. 