---
title: "Homework 1 Rubric"
html: default
pdf: default
---

This is the grading rubric for [Homework 1](../hw/hw01/hw01.qmd). The rubric does not provide specifics

## Rubric

### Problem 1 (20 Points)

#### Problem 1.1 (10 points)

| Needs Improvement (0-3) | Developing (4-6) | Above Average (7-9) | Excellent (10) |
|:------------------------|:-----------------|:--------------------|:---------------|
| Missing or logic error incorrectly identified. | Logic error correctly identifed, but unclear description which makes the connection to the code tenuous. | Logic error correctly identified and connected to the code, but some lack of clarity in the description. | Logic error correctly identified and clearly described, including where it occurs in the code. |

#### Problem 1.2 (5 points)

| Needs Improvement (0-2) | Above Average (3-4) | Excellent (5) |
|:------------------------|:-----------------|:--------------------|
| No fixed code provided or new function does not fix the underlying error. | Code fixes the underlying error, but has no comments or additional mistakes. | Code fixes the error without other bugs and includes comments indicating the change. |

#### Problem 1.3 (5 points)

| Needs Improvement (0-2) | Above Average (3-4) | Excellent (5) |
|:------------------------|:-----------------|:--------------------|
| Fixed function not used. | Fixed function used, but incorrectly applied. | Fixed function used and produces the correct value. |

### Problem 2 (20 points)


#### Problem 2.1 (10 points)

| Needs Improvement (0-3) | Developing (4-6) | Above Average (7-9) | Excellent (10) |
|:------------------------|:-----------------|:--------------------|:---------------|
| Missing or logic error incorrectly identified. | Logic error correctly identifed, but unclear description which makes the connection to the code tenuous. | Logic error correctly identified and connected to the code, but some lack of clarity in the description. | Logic error correctly identified and clearly described, including where it occurs in the code. |

#### Problem 2.2 (5 points)

| Needs Improvement (0-2) | Above Average (3-4) | Excellent (5) |
|:------------------------|:-----------------|:--------------------|
| No fixed code provided or new function does not fix the underlying error. | Code fixes the underlying error, but has no comments or additional mistakes. | Code fixes the error without other bugs and includes comments indicating the change. |

#### Problem 2.3 (5 points)

| Needs Improvement (0-2) | Above Average (3-4) | Excellent (5) |
|:------------------------|:-----------------|:--------------------|
| Fixed function not used. | Fixed function used, but incorrectly applied. | Fixed function used and produces the correct value. |

### Problem 3 (20 points)

#### Problem 3.1 (10 points)

| Needs Improvement (0-3) | Developing (4-6) | Above Average (7-9) | Excellent (10) |
|:------------------------|:-----------------|:--------------------|:---------------|
| Answer missing or explained purpose is incorrect. | Explanation of purpose is vague and does not reflect understanding of what code does. | Explanation of purpose is mostly correct, but may have some slight vagueness or lack of clarity. | Purpose is explained accurately and clearly. |

#### Problem 3.2 (10 points)

| Needs Improvement (0-3) | Developing (4-6) | Above Average (7-9) | Excellent (10) |
|:------------------------|:-----------------|:--------------------|:--------------|
| Comments missing or do not help explain the purpose of the code. | Comments are incomplete, but the ones that are present are helpful. | Comments generally provided and helpful, but some are not clear. | Comments clearly explain why and how the code works. |

### Problem 4 (40 points)

#### Problem 4.1 (10 points)

| Needs Improvement (0-3) | Developing (4-6) | Above Average (7-9) | Excellent (10) |
|:------------------------|:-----------------|:--------------------|:---------------|
| Labels missing or have no or little relationship to the problem description. | Labels reflect the correct quantities but are misapplied to the system diagram. | Labels have some slight mistakes but reflect understanding of description and diagram. | Labels are correct and appear on the right vertices. |

#### Problem 4.2 (10 points)

| Needs Improvement (0-3) | Developing (4-6) | Above Average (7-9) | Excellent (10) |
|:------------------------|:-----------------|:--------------------|:--------------|
| Model is missing or does not reflect problem description. | Model missing components or equations have large errors and/or no or little justification from the stated problem. | Equations are generally correct and but may include some small mistakes or justification is vague at points. | Equations are correct and well-justified with reference to the problem description. |

#### Problem 4.3 (10 points)

| Needs Improvement (0-3) | Developing (4-6) | Above Average (7-9) | Excellent (10) |
|:------------------------|:-----------------|:--------------------|:--------------|
| Code is missing or contains serious mistakes that prevent it from running. | Function runs, but has serious errors which prevent it from implementing the derived equations. | Function contains minor errors or is missing clarifying comments. | Function correctly implements model and is appropriately commented. |

#### Problem 4.4 (10 points)

| Needs Improvement (0-3) | Developing (4-6) | Above Average (7-9) | Excellent (10) |
|:------------------------|:-----------------|:--------------------|:--------------|
| Experiments or explanations are missing (*e.g.* there is only a reporting of results) or aren't reflective of the questions. | Experiments present and sufficient but explanations are sketchy and do not address the questions. | Experiments present and sufficient, but questions are not fully engaged with, or minor errors (plot labels not labeled, etc) in presentation. | Experiments present and sufficient and discussion of questions is complete. |
