---
title: "Homework 2 Rubric"
html: default
pdf: default
---

This is the grading rubric for [Homework 2](../hw/hw02/hw02.qmd). The rubric does not provide specifics, but should give an idea of what a complete solution looks like and how different components are prioritized and weighted.

The assignment is out of a total of 40 points.

## Rubric

General points will be deducted for the following:

- Late submission (10% per day);
- Untagged answers in Gradescope (10% penalty);
- Non-referenced consulted sources (penalty depending on severity).

### Problem 1 (8 Points)

| Missing (0) | Needs Improvement (1-2) | Developing (3-4) | Above Average (5-6) | Excellent (7-8) |
|:-----------------|:-----------------|:-----------------|:-----------------|:-----------------|
| Solution missing or unrelated to problem description. | Code does not work (throws an error) or implements a different model.  | Code runs but has a major bug or logical error which makes the answer to the minimum value incorrect.  | Code implements the model correctly and gets the right answer but is uncommented or unclear. | Code works or may contain a minor bug. |

### Problem 2 (4 points)

| Missing (0) | Needs Improvement (1) | Developing (2) | Above Average (3) | Excellent (4) |
|:-----------------|:-----------------|:-----------------|:-----------------|:-----------------|
| Plot not provided or does not seem related to the problem. | Plot is missing requested elements or plotted series has major mistakes. | Plot is missing major components, such as axis labels or legends. | Plot is missing minor components, such as units, or has minor mistakes in the plotted series. | Plot is clearly and completely labelled and is correct. |

### Problem 3 (3 points)

| Needs Improvement (0) | Developing (1) | Above Average (2) |
|:------------------------|:-----------------|:--------------------|
| Problem missing or no solution provided using model from Problem 1. | Model used to provide wrong answer. | Correct solution obtained. |

### Problem 4 (5 points)

| Missing (0) | Developing (1-2) | Above Average (3-4) | Excellent (5) |
|:-----------------|:-----------------|:-----------------|:-----------------|
| Solution not provided or does not seem related to the problem. | Solution is provided, but contains major mistakes in the approach. | Solution contains minor mistakes, or is inappropriately precise (in either direction). | Solution is correct and is correctly implemented. |

### Problem 5 (5 points)

| Missing (0) | Developing (1-2) | Above Average (3-4) | Excellent (5) |
|:-----------------|:-----------------|:-----------------|:-----------------|
| Solution not provided or does not seem related to the problem. | Solution is provided, but contains major mistakes in the approach. | Solution contains minor mistakes, or is inappropriately precise (in either direction). | Solution is correct and is correctly implemented. |

### Problem 6 (5 points)

| Missing (0) | Developing (1-2) | Above Average (3-4) | Excellent (5) |
|:-----------------|:-----------------|:-----------------|:-----------------|
| Answer not provided or does not seem related to the problem. | Answer is provided, but is not or is poorly justified. | Answer is not complete and misses some additional information. | Complete answer provided. |

### Problem 7 (5 points)

| Missing (0) | Developing (1-2) | Above Average (3-4) | Excellent (5) |
|:-----------------|:-----------------|:-----------------|:-----------------|
| Solution not provided or does not seem related to the problem. | Solution is provided, but contains major mistakes in the approach. | Solution contains minor mistakes, or is inappropriately precise (in either direction). | Solution is correct and is correctly implemented. |

### Problem 8 (5 points)

| Missing (0) | Developing (1-2) | Above Average (3-4) | Excellent (5) |
|:-----------------|:-----------------|:-----------------|:-----------------|
| Solution not provided or does not seem related to the problem. | Solution is provided, but contains major mistakes in the approach. | Solution contains minor mistakes, or is inappropriately precise (in either direction). | Solution is correct and is correctly implemented. |
