---
title: "Homework 3 Rubric"
html: default
pdf: default
---

This is the grading rubric for [Homework 3](../hw/hw03/hw03.qmd). The rubric does not provide specifics, but should give an idea of what a complete solution looks like and how different components are prioritized and weighted.

The assignment is out of a total of 40 points.

## Rubric

General points will be deducted for the following:

- Late submission (10% per day);
- Untagged answers in Gradescope (10% penalty);
- Non-referenced consulted sources (penalty depending on severity).

### Problem 1 (12 Points)

#### Problem 1.1 (3 points)

| Missing (0) | Needs Improvement (1) | Developing (2) | Above Average (3) | 
|:-----------------|:-----------------|:-----------------|
| Solution or histogram missing or unrelated to problem description. | Wrong number of samples or distribution specified incorrectly. | Histogram missing plotting elements (axis labels, units, etc, as appropriate) | Sampling and histogram completed correctly. | 

#### Problem 1.2 (5 points)

| Missing (0) | Needs Improvement (1) | Developing (2) | Above Average (3-4) | Excellent (5) |
|:-----------------|:-----------------|:-----------------|:-----------------|:-----------------|
| Solution missing or does not seem related to the problem. | Major errors in uncertainty propagation (e.g. wrong parameter or wrong distribution).| No major errors in uncertainty propagation, but plot is missing or missing key requested elements. | Minor problems with plot (missing labels, units, etc) and/or uncertainty propagation. | Uncertainties propagated through model correctly and plot contains all requested elements. |

#### Problem 1.3 (4 points)

| Missing (0) | Needs Improvement (1) | Developing (2) | Above Average (3) | Excellent (4) |
|:------------------------|:-----------------|:--------------------|:--------------------|:--------------------|
| Histogram missing or unrelated to problem description.  | Histogram missing plotting elements (axis labels, units, etc, as appropriate). | Histogram is of wrong quantity. | Sampling and histogram completed correctly but discussion of distributions is missing or unclear. | Sampling and histogram completed correctly and clear comparison of distributions provided. | 

### Problem 2 (15 points)

#### Problem 2.1 (5 points)

| Missing (0) | Developing (1-2) | Above Average (3-4) | Excellent (5) |
|:-----------------|:-----------------|:-----------------|:-----------------|
| Solution not provided or does not seem related to the problem. | Model developed but has major bugs which prevent it from implementing the equations. | Model has minor bugs and/or is missing test. | Model correctly implements equation and is tested. |

### Problem 2.2 (5 points)

| Missing (0) | Needs Improvement (1) | Developing (2) | Above Average (3-4) | Excellent (5) |
|:-----------------|:-----------------|:-----------------|:-----------------|
| Solution missing or unrelated to problem description. | Model is evaluated using wrong temperature ensemble. | Plot is missing but model evaluation is provided using the correct ensemble. | Minor problems in model evaluation and/or plot. | All elements executed correctly. |

#### Problem 2.3 (5 points)

| Missing (0) | Needs Improvement (1) | Developing (2-3) | Above Average (4) | Excellent (5) |
|:------------------------|:-----------------|:--------------------|:--------------------|:--------------------|
| Histogram missing or unrelated to problem description.  | Histogram missing plotting elements (axis labels, units, etc, as appropriate). | Histogram is of wrong quantity. | Sampling and histogram completed correctly but discussion is missing or unclear. | Sampling and histogram completed correctly and clear discussion provided. | 

### Problem 3 (13 points)

#### Problem 3.1 (2 points)

| Missing (0) | Developing (1) | Above Average (2) 
|:-----------------|:-----------------|:-----------------|
| Solution not provided, incomplete, or does not seem related to the problem. | Approach complete but unclear or contains small mistakes.  | Approach correctly and clearly describes steps. |

#### Problem 3.2 (3 points)

| Missing (0) | Needs Improvement (1) | Developing (2) | Above Average (3)  |
|:------------------------|:-----------------|:--------------------|:--------------------|:--------------------|
| Histogram missing or unrelated to problem description.  | Histogram missing plotting elements (axis labels, units, etc, as appropriate). | Histogram is of wrong quantity. | Sampling and histogram completed correctly. 

#### Problem 3.3 (5 points)

| Missing (0) | Needs Improvement (1-2) | Developing (2-3) | Above Average (4-5) | 
|:------------------------|:-----------------|:--------------------|:--------------------|
| Solution missing or unrelated to problem description.  | Wrong analysis framework used to assess probabilities (points based on severity of problem). | Minor problem with probability analysis (e.g. wrong threshold, lack of unit conversion, etc). | Analysis done correctly, possibly with comparison to reliability standard. | 

#### Problem 3.4 (3 points)

| Missing (0) | Developing (1) | Above Average (2) | Excellent (3)  |
|:------------------------|:-----------------|:--------------------|:--------------------|:--------------------|
| Solution missing or unrelated to problem description.  | Recommendation made but is not clearly based on the prior analysis. | Recommendation made based on prior analysis but neglects other relevant information that might influence it. | Discussion includes consideration of other potentially relevant information.
