---
title: "Homework 5 Rubric"
html: default
pdf: default
---

This is the grading rubric for [Homework 5](../hw/hw05/hw05.qmd). The rubric does not provide specifics, but should give an idea of what a complete solution looks like and how different components are prioritized and weighted.

The assignment is out of a total of 40 points.

## Rubric

General points will be deducted for the following:

- Late submission (10% per day);
- Untagged answers in Gradescope (10% penalty);
- Non-referenced consulted sources (penalty depending on severity).

### Problem 1 (22 Points)

#### Problem 1.1 (3 points)

| Missing (0) | Needs Improvement (1) | Developing (2) | Above Average (3) |
|:-----------------|:-----------------|:-----------------|:-----------------|
Solution missing or unrelated to problem description, or solutions provided without justification. | Calculations contain conceptual mistakes (*e.g.* wrong formulas). | Minor mistake in calculations (*e.g.* algebra mistake). | Calculations done correctly and free from conceptual mistakes. |

#### Problem 1.2 (2 points)

| Missing or Needs Improvement (0) | Needs Improvement (1)  | Above Average (2) | 
|:-----------------|:-----------------|:-----------------|
| Solution missing or seemingly unrelated to problem description, or variable list missing definitions. | Variable list incomplete or missing units. | Variable list contains all needed variables and enough detail to know what the variables represent, including units. | 

#### Problem 1.3 (3 points)

| Missing (0) | Needs Improvement (1) | Developing (2) | Above Average (3) | 
|:-----------------|:-----------------|:-----------------|:-----------------|
| Solution missing or does not seem related to the problem, or uses notation which was not established in Problem 1.1 or this one. | Objective function contains major conceptual mistakes, such as missing key components. | Objective function contains all needed components but may include minor conceptual mistakes, such as overlooking a term. | Objective function is complete and may include very minor mistakes, such as an incorrect coefficient. | 

#### Problem 1.4 (4 points)

| Missing (0) | Needs Improvement (1) | Developing (2) | Above Average (3) | Excellent (4) |
|:------------------------|:-----------------|:--------------------|:--------------------|:--------------------|
| Solution missing or unrelated to problem description.  | Not all constraints included, and the ones that are included have conceptual mistakes. | Not all constraints included (enough to not properly constrain the problem), but the ones that are included are correct, and constraints may be missing derivations or justifications.  | All needed constraints included, but some include conceptual mistakes in how they're specified or derived/justified. | All needed constraints included with appropriate derivation and justification and contain at most minor mistakes.

#### Problem 1.5 (3 points)

| Missing or Needs Improvement (0) |  Developing (1) | Above Average (2) | Excellent (3) |
|:------------------------|:-----------------|:--------------------|:--------------------|:--------------------|
| Solution missing or unrelated to problem formulation from Problems 1.1--1.3.  | Major mistakes in problem program, such as missing or mis-specified objectives, variables, or constraints. | Minor mistakes in problem program, such as typos, or program is missing comments and is unclear to follow.  | Code appropriately encodes specified optimization problem and is appropriately commented so it is easy to follow. | 

#### Problem 1.6 (2 points)

| Missing (0) or Needs Improvement (0) | Developing (1) | Above Average (2) |
|:------------------------|:-----------------|:--------------------| 
| Solution missing or unrelated to problem description.  | Optimal solution found but details are incomplete, queried incorrectly, or presented unclearly. | Optimal solution found and reporting clear and complete. |

#### Problem 1.7 (5 points)

| Missing (0) | Needs Improvement (1) | Developing (2-3) | Above Average (4) | Excellent (5) |
|:------------------------|:-----------------|:--------------------|:--------------------|:--------------------|
| Solution missing or unrelated to problem description.  | No or unclear analysis provided. | Analysis provided, but limited and doesn't address prompts, or diagram is missing. | Analysis provided and clear, but analysis and/or diagram contains small errors. | Clear analysis provided along with correct diagram. 


### Problem 2 (18 points)

#### Problem 2.1 (5 points)

| Missing (0) | Needs Improvement (1) | Developing (2) | Above Average (3-4) | Excellent (5) | 
|:------------------------|:-----------------|:--------------------|:--------------------|:--------------------|
| Solution missing, unrelated to problem description, or complete program not provided.  | Provided changes are not justified or explained and/or contain major conceptual mistakes. | Provided changes are justified (maybe with minor mistakes), but some changes missing. | Provided changes are justified but with minor mistakes in the justification or the new equations and all needed changes are provided.  | All changes correctly provided with explanations. |


### Problem 2.2 (3 points)

| Missing or Needs Improvement (0) |  Developing (1) | Above Average (2) | Excellent (3) |
|:------------------------|:-----------------|:--------------------|:--------------------|:--------------------|
| Solution missing or unrelated to problem formulation from Problems 1.1--1.3.  | Major mistakes in problem program, such as missing or mis-specified objectives, variables, or constraints. | Minor mistakes in problem program, such as typos, or program is missing comments and is unclear to follow.  | Code appropriately encodes specified optimization problem and is appropriately commented so it is easy to follow. |

#### Problem 2.3 (5 points)

| Missing (0) | Needs Improvement (1) | Developing (2-3) | Above Average (4) | Excellent (5) |
|:------------------------|:-----------------|:--------------------|:--------------------|:--------------------|
| Solution missing or unrelated to problem description.  | Optimal solution found but with no details on the solution. | Optimal solution found but details are incomplete, queried incorrectly, or presented unclearly. | Solution found but some slight mistakes in the solution details or diagram missing. | Optimal solution found but may be minor mistakes in the objective value or diagram. | Optimal solution found and subsequent analysis is correct.

#### Problem 2.4 (5 points)

| Missing (0) | Needs Improvement (1) | Developing (2-3) | Above Average (4) | Excellent (5) |
|:------------------------|:-----------------|:--------------------|:--------------------|:--------------------|
| Solution missing or unrelated to problem description.  | Recommendation provided with no justification. | Recommendation provided but relationship to solution is weak or unclear. | Recommendation provided which is connected to the solution but might benefit from drawing on broader considerations. | Recommendation provided and fully justified, including drawing on broader systems considerations. |
