---
title: "Lab 3 Rubric"
html: default
pdf: default
---

This is the grading rubric for [Lab 3](../labs/lab03/lab03.qmd). The rubric does not provide specifics, but should give an idea of what a complete solution looks like and how different components are prioritized and weighted.

The assignment is out of a total of 10 points.
`
## Rubric`

### Problem 1 (5 Points)

#### Problem 1.1 (1 points)

| Missing or Needs Improvement (0) | Above Average (1) |
|:------------------------|:-----------------|
| Problem missing or variables not well defined. | Decision variables defined along with units and meaning; minor mistakes ok. |

#### Problem 1.2 (2 points)

| Missing or Needs Improvement (0) | Above Average (1)  |
|:------------------------|:-----------------|
| No answer, major mistakes in objective function provided, or objective function provided without derivation or justification. | Objective function provided with derivation; minor mistakes ok. | 

#### Problem 1.3 (2 points)

| Missing (0) | Needs Improvement (1) | Above Average (2) |
|:------------------------|:-----------------|:--------------------|
| No answers or major conceptual errors on constraint derivation. | Constraint set mostly but not complete. | Complete constraint set provided; minor mistakes ok. |

#### Problem 1.4 (1 points)

| Missing or Needs Improvement (0) | Above Average (1)  |
|:------------------------|:-----------------|
| No answer or problem not put in standard form. | Problem provided in standard form, consistent with the prior answers. | 

### Problem 2 (5 points)


#### Problem 2.1 (2 points)

| Missing (0) | Needs Improvement (1) | Above Average (2) | 
|:------------------------|:-----------------|:--------------------|
| Solution missing or implementation unrelated to problem. | Code provided but has major problems (throws an error). | Code provided which correctly implements the problem (per Problem 1.4) and does not throw an error. | 

#### Problem 2.2 (1 points)

| Missing or Needs Improvement (0) | Above Average (1) | 
|:------------------------|:-----------------|
| Solution missing components (for example, decision variables not provided). | Complete solution provided which includes optimal objective value and decision variable values. |


#### Problem 2.3 (1 points)

| Missing or Needs Improvement (0) | Above Average (1) | 
|:------------------------|:-----------------|
| Solution missing or shadow price not queried or interpreted properly. | Correct solution provided. |

#### Problem 2.4 (1 points)

| Missing or Needs Improvement (0) | Above Average (1) | 
|:------------------------|:-----------------|
| Solution missing or no interpretation of queried values provided. | Answer provided which answers the question posed. |

