---
title: "Homework 1 Rubric"
html: default
pdf: default
---

This is the grading rubric for [Lab 2](../labs/lab02/lab02.qmd). The rubric does not provide specifics, but should give an idea of what a complete solution looks like and how different components are prioritized and weighted.

The assignment is out of a total of 10 points.
`
## Rubric`

### Problem 1 (5 Points)

#### Problem 1.1 (1 points)

| Missing or Needs Improvement (0) | Above Average (1) |
|:------------------------|:-----------------|
| Problem missing or major error in code. | Code runs and has the correct logic to simulate the game |

#### Problem 1.2 (2 points)

| Missing (0) | Needs Improvement (1) | Above Average (2) |
|:------------------------|:-----------------|:--------------------|
| No plot provided or plot does not visualize what was asked for. | Plot is related to the game simulations but has key issues prohibiting interpretability of results (unlabeled axes, etc). | Plot is easy to interpret and graphs the correct quantities. |

#### Problem 1.3 (2 points)

| Missing (0) | Needs Improvement (1) | Above Average (2) |
|:------------------------|:-----------------|:--------------------|
| Analysis missing or unrelated to the plot. | Analysis does not match plot or is merely superficial (for example, identifying point of rough convergence without discussing earlier period). | Analysis matches the plot and covers everything asked for. |

### Problem 2 (5 points)


#### Problem 2.1 (3 points)

| Missing (0) | Needs Improvement (1) | Above Average (2) | Excellent (3) |
|:------------------------|:-----------------|:--------------------|:---------------|
| Problem missing or code is not related to the problem. | Code has major logic or syntax errors and/or justification of the number of samples is missing. | Code has a minor error which prevents getting the right results or justification of the number of samples is weak (e.g. not related to any analysis of convergence). | Code works properly and clear justification of number of samples is presented, drawing on evidence. |

#### Problem 2.2 (2 points)

| Missing (0) | Needs Improvement (1) | Above Average (2) |
|:------------------------|:-----------------|:--------------------|
| Plot is missing or is unrelated to the problem. | Plot is present but has issues which limit interpretabiity (e.g. unlabeled axes) or there is no analysis of the result. | Plot answers the question and is easily interpretable, and there is a discussion of the results.  |
