---
title: "Project Poster Rubric"
html: default
pdf:
    documentclass: article
    geometry:
        - margin=1in  
    include-in-header:
        text: |
            \renewcommand\toprule[2]\relax
            \renewcommand\bottomrule[2]\relax
    filters:
        - ../_assets/filters/columns-to-tables.lua
---

## Rubric

The poster is graded out of a total of 20 points. 

General points will be taken off for:

- Missing check-in meeting (-5 points);
- Missing units where appropriate (-1-2 points depending on frequency);
- Unlabeled figures or figures without captions (-1 point)

### System Overview (3 points)

| Needs Improvement (0) | Developing (1) | Above Average (2) | Excellent (3) |
|:------------------------|:-----------------|:--------------------|:---------------|
| No overview of system, or system overview neglects description of relevant components and dynamics. | System overview is present, but includes errors or is too vague to connect to project. | System overview is present but contains minor inaccuracies or gaps. | Overview provides clear idea of system components and dynamics. | 

### Problem Framing and Motivation (3 points)

| Needs Improvement (0) | Developing (1) | Above Average (2) | Excellent (3) |
|:------------------------|:-----------------|:--------------------|:---------------|
| No objective or key question is clearly specified. | Objective or key question is specified but is not motivated by or connected to the system overview. | Objective or key question specification is unclear or vague. | Clear presentation of objective or key question with connection to the underlying system. | 

## Method Appropriateness (2 points)

| Needs Improvement (0) | Developing (1) | Above Average (2) |
|:------------------------|:-----------------|:--------------------|
| Methods are not aligned with the project objective. | Methods are somewhat aligned with project objective, but this may be unclear. | Methods are appropriate for the question. | 

## Assumptions (2 points)

| Needs Improvement (0) | Developing (1) | Above Average (2) |
|:------------------------|:-----------------|:--------------------|
| No discussion of key assumptions. | Some key assumptions are left implicit. | Key assumptions are specified and justified.  | 

## Results (3 point)

| Needs Improvement (0) | Developing (1) | Above Average (2) | Excellent (3) |
|:------------------------|:-----------------|:-----------------|:-----------------|
| Results are missing or do not seem to follow from the methods. | Results are unclearly presented but make sense given the methods. | Results make sense given the methods but do not quite address the project question as articulated. | Results follow from the methods and address the project question. |

## Conclusions (3 point)

| Needs Improvement (0) | Developing (1) | Above Average (2) | Excellent (3) |
|:------------------------|:-----------------|:-----------------|:-----------------|
| Conclusions are not presented or are unclear. | Conclusions do not accurately summarize results and implications for the question. | Conclusions may be somewhat superficial (*e.g.* they just repeat the findings without synthesis or reflection on methods). | Conclusions are clearly presented, synthesize the findings, and accurately summarize the results. |

## Discussion (3 points)

| Needs Improvement (0) | Developing (1) | Above Average (2) | Excellent (3) |
|:------------------------|:-----------------|:-----------------|:-----------------|
| No relevant discussion included. | Discussion is vague and does not reflect on how student extended their understanding of the class material. | Discussion is unclear in places but describes how student extended class material. | Discussion clearly reflects the findings and assumptions in the context of class material. |

## References (1 point)

| Needs Improvement (0) | Above Average (1) |
|:------------------------|:-----------------|
| No references are included. | Key references are included (note: not all references are needed in the interest of space). |