---
title: "Regulations Report Rubric"
html: default
pdf:
    documentclass: article
    geometry:
        - margin=1in  
    include-in-header:
        text: |
            \renewcommand\toprule[2]\relax
            \renewcommand\bottomrule[2]\relax
    filters:
        - ../_assets/filters/columns-to-tables.lua
---

## Rubric

The report is graded out of a total of 20 points.

### Problem Background (3 points)

| Needs Improvement (0) | Developing (1) | Above Average (2) | Excellent (3) |
|:------------------------|:-----------------|:--------------------|:---------------|
| No description of background, or description does not make the problem or regulatory context clear. | Describes the broad regulatory context clearly and includes specific concerns or motivating incidents. | Motivates need for regulatory action, but not clearly. | Need for regulatory action is clearly articulated in light of context and concerns. | 

### Regulatory Purpose (4 points)

| Needs Improvement (0) | Developing (1) | Above Average (2) | Excellent (4) |
|:------------------------|:-----------------|:--------------------|:---------------|
| Missing or no specifics provided. | Provides some details but writing is unclear and not tied to specific aims. | Purpose and aims of regulation are clearly articulated. | Purpose of regulation is tied clearly to the background context. | 

## Current State (4 points)

| Needs Improvement (0) | Developing (1) | Above Average (2) | Excellent (4) |
|:------------------------|:-----------------|:--------------------|:---------------|
| Missing or no specifics provided. | Current state of the regulation is provided but is unclear, and/or is derived from inappropriate sources. | Description of regulation is clear, but is largely reproduced from a single (appropriate) source. | Description clearly synthesizes multiple appropriate sources in own words.| 

## Descriptive Timeline (4 points)

| Needs Improvement (0) | Developing (1) | Above Average (3) | Excellent (4) |
|:------------------------|:-----------------|:--------------------|:---------------|
| Missing or no specifics provided. | Fewer than three rule-making instances are provided without justification and evidence that fewer have occurred. | At least three rule-making instances are provided and are sufficiently detailed to understand the relevant changes, but feel disconnected. | Rule-making instances are well-motivated and connected to the broader narrative in a coherent timeline.  | 

## Model Incorporation (5 points)

| Needs Improvement (0) | Developing (1) | Above Average (3) | Excellent (5) |
|:------------------------|:-----------------|:--------------------|:---------------|
| Missing. | Some attempt to incorporate the regulation into the systems model is provided, but missing specifics or is disconnected from its purpose and aims. | The regulation's incorporation into the problem is specifically defined or justification seems arbitrary. | The regulation's incorporation into the problem is well connected to the broader narrative about its purpose and aims.  | 