{
  "hash": "a1892e760ad170dc8530de62a10a74e6",
  "result": {
    "markdown": "---\ntitle: \"Plume Models: Dispersion and Examples\"\nsubtitle: \"Lecture 20\"\nauthor: \"Vivek Srikrishnan\"\ncourse: \"BEE 4750\"\ninstitution: \"Cornell University\"\ndate: \"October 20, 2023\"\nformat:\n    revealjs:\n        slide-number: c/t\n        show-slide-number: all\n        center-title-slide: true\n        width: 1280\n        height: 720\n        transition: none\n        toc: true\n        toc-depth: 1\n        toc-title: \"Overview\"\n        history: false\n        link-external-newwindow: true\n        theme: ../sass/slides.scss\n        footer: \"[BEE 4750, Environmental Systems Analysis](https://viveks.me/environmental-systems-analysis)\"\n        template-partials:\n            - title-slide.html\n        menu:\n            numbers: true\n        html-math-method: mathjax\n        include-in-header: mathjax-config.html\n        date-format: long\n\nexecute:\n    freeze: auto\n---\n\n\n\n\n\n# Review and Questions\n\n## Gaussian Plume for Air Pollution Dispersion\n\n- Used for point sources.\n- Typically for continuous emissions from an elevated source.\n\n## Gaussian Plume Model\n\n| Variable | Meaning | \n|:--------:|:--------|\n| $C$ | Concentration (g/m$^3$) | \n| $Q$ | Emissions Rate (g/s) | \n| $H$ | Effective Source Height (m) | \n| $u$ | Wind Speed (m/s) |\n| $y, z$ | Crosswind, Vertical Distance (m)\n\n\n## Gaussian Plume Model\n\n![Gaussian Plume Distribution](figures/air-pollution-plume-dist.png)\n\n\n## Gaussian Plume Model With Ground Reflection\n\n$$\\begin{aligned}\nC(x,y,z) = &\\frac{Q}{2\\pi u \\sigma_y \\sigma_z} \\exp\\left(\\frac{-y^2}{2\\sigma_y^2} \\right) \\times \\\\\\\\\n& \\quad \\left[\\exp\\left(\\frac{-(z-H)^2}{2\\sigma_z^2}\\right) + \\exp\\left(\\frac{-(z+H)^2}{2\\sigma_z^2}\\right) \\right]\n\\end{aligned}$$\n\n\n## Questions\n\n:::: {.columns .center}\n::: {.column width=\"40%\"}\n![](images/vsrikrish-poll.png){fig-alt=\"Poll Everywhere QR Code\" fig-align=\"center\" width=\"100%\"}\n:::\n::: {.column width=60%}\n**Text**: VSRIKRISH to 22333\n\n**URL**: [https://pollev.com/vsrikrish](https://pollev.com/vsrikrish)\n<br><br>\n[See Results](https://www.polleverywhere.com/multiple_choice_polls/qKeig0hHShZYHAOmvZtZm?preview=true&controls=none){preview-link=\"true\"}\n:::\n::::\n\n\n\n# Dispersion\n\n## Estimating Dispersion \"Spread\"\n\nValues of $\\sigma_y$ and $\\sigma_z$ matter substantially for modeling plume spread downwind. What influences them?\n\n## Estimating Dispersion \"Spread\"\n\n**Main contribution**: atmospheric stability\n\n- Greater stability &Rightarrow; less vertical/cross-wind dispersion.\n\n- Pasquill (1961): Six stability classes.\n\n## Estimating Dispersion \"Spread\"\n\nContributors to atmospheric stability:\n\n- Temperature gradient\n- Wind speed\n- Solar radiation\n- Cloud cover\n- Richardson number (buoyancy / flow shear)\n\n## Atmospheric Stability Classes\n\nClass | Stability | Description |\n:----:|:----------|:-----------|\nA | Extremely unstable | Sunny summer day \nB | Moderately unstable | Sunny & warm |\nC | Slightly unstable | Partly cloudy day |\nD | Neutral | Cloudy day or night |\nE | Slightly stable | Partly cloudy night |\nF | Moderately stable | Clear night |\n\n::: {.caption}\nSource: <https://courses.ecampus.oregonstate.edu/ne581/eleven/>\n:::\n\n## Estimating Dispersion \"Spread\"\n\n$$\\begin{aligned}\n\\sigma_y &= ax^{0.894} \\\\\n\\sigma_z &= cx^d + f\n\\end{aligned}$$\n\n![Dispersion Coefficients](figures/plume-dispersion.png)\n\n::: {.caption}\nSource: <https://courses.washington.edu/cee490/DISPCOEF4WP.htm>\n:::\n\n**Note**: here $x$ is in km, while in the plume equation $y$, $z$ are in m!\n\n\n## Estimating Dispersion \"Spread\"\n\nThen take estimates for $\\sigma_y$ and $\\sigma_z$ and plug into plume dispersion equation\n\n$$\\begin{aligned}\nC(x,y,z) = &\\frac{Q}{2\\pi u {\\color{red}\\sigma_y \\sigma_z}} \\exp\\left(\\frac{-y^2}{2{\\color{red}\\sigma_y^2}} \\right) \\times \\\\\\\\\n& \\quad \\left[\\exp\\left(\\frac{-(z-H)^2}{2{\\color{red}\\sigma_z^2}}\\right) + \\exp\\left(\\frac{-(z+H)^2}{2{\\color{red}\\sigma_z^2}}\\right) \\right]\n\\end{aligned}$$\n\n\n# Multiple Point Sources\n\n## Managing Multiple Plumes\n\nWe could use a Gaussian plume to simulate the effect of a single source, but often we:\n\n- Have multiple sources that we need to manage;\n- Care about compliance with regulatory standards at a particular important receptor.\n\n## Multiple Point Source Example\n\nTake three sources of SO~2~ (air quality standard 150 $\\mu\\text{g/m}^3$):\n\n| Source | Emissions (kg/day) | Effective Height (m) | Removal Cost (\\$/kg)\n|:---:|---------:|-----------:|-----------:|\n| 1 | 34,560 | 50 | 0.20 |\n| 2 | 172,800 | 200 | 0.45 |\n| 3 | 103,680 | 30 | 0.60 |\n\nand five receptors at ground level with $u = 1.5$ m/s.\n\n## Multiple Point Source Example\n\n:::: {.columns}\n::: {.column width=40%}\n\nOur goal: \n\nMinimize cost of removing SO~2~ from the plume sources to ensure all receptors are not exposed beyond the 150 $\\mu\\text{g/m}^3$ standard.\n\n:::\n::: {.column width=60%}\n\n::: {#45ea52c9 .cell execution_count=3}\n\n::: {.cell-output .cell-output-display execution_count=297}\n```{=html}\n<?xml version=\"1.0\" encoding=\"utf-8\"?>\n<svg xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\" width=\"600\" height=\"500\" viewBox=\"0 0 2400 2000\">\n<defs>\n  <clipPath id=\"clip510\">\n    <rect x=\"0\" y=\"0\" width=\"2400\" height=\"2000\"/>\n  </clipPath>\n</defs>\n<path clip-path=\"url(#clip510)\" d=\"M0 2000 L2400 2000 L2400 0 L0 0  Z\" fill=\"#ffffff\" fill-rule=\"evenodd\" fill-opacity=\"1\"/>\n<defs>\n  <clipPath id=\"clip511\">\n    <rect x=\"480\" y=\"0\" width=\"1681\" height=\"1681\"/>\n  </clipPath>\n</defs>\n<defs>\n  <clipPath id=\"clip512\">\n    <rect x=\"296\" y=\"47\" width=\"2058\" height=\"1693\"/>\n  </clipPath>\n</defs>\n<path clip-path=\"url(#clip510)\" d=\"M296.206 1739.26 L2352.76 1739.26 L2352.76 47.2441 L296.206 47.2441  Z\" fill=\"#ffffff\" fill-rule=\"evenodd\" fill-opacity=\"1\"/>\n<polyline clip-path=\"url(#clip512)\" style=\"stroke:#000000; stroke-linecap:round; stroke-linejoin:round; stroke-width:2; stroke-opacity:0.1; fill:none\" points=\"389.686,1739.26 389.686,47.2441 \"/>\n<polyline clip-path=\"url(#clip512)\" style=\"stroke:#000000; stroke-linecap:round; stroke-linejoin:round; stroke-width:2; stroke-opacity:0.1; fill:none\" points=\"857.083,1739.26 857.083,47.2441 \"/>\n<polyline clip-path=\"url(#clip512)\" style=\"stroke:#000000; stroke-linecap:round; stroke-linejoin:round; stroke-width:2; stroke-opacity:0.1; fill:none\" points=\"1324.48,1739.26 1324.48,47.2441 \"/>\n<polyline clip-path=\"url(#clip512)\" style=\"stroke:#000000; stroke-linecap:round; stroke-linejoin:round; stroke-width:2; stroke-opacity:0.1; fill:none\" points=\"1791.88,1739.26 1791.88,47.2441 \"/>\n<polyline clip-path=\"url(#clip512)\" style=\"stroke:#000000; stroke-linecap:round; stroke-linejoin:round; stroke-width:2; stroke-opacity:0.1; fill:none\" points=\"2259.28,1739.26 2259.28,47.2441 \"/>\n<polyline clip-path=\"url(#clip510)\" style=\"stroke:#000000; stroke-linecap:round; stroke-linejoin:round; stroke-width:4; stroke-opacity:1; fill:none\" points=\"296.206,1739.26 2352.76,1739.26 \"/>\n<polyline clip-path=\"url(#clip510)\" style=\"stroke:#000000; stroke-linecap:round; stroke-linejoin:round; stroke-width:4; stroke-opacity:1; fill:none\" points=\"389.686,1739.26 389.686,1720.36 \"/>\n<polyline clip-path=\"url(#clip510)\" style=\"stroke:#000000; stroke-linecap:round; stroke-linejoin:round; stroke-width:4; stroke-opacity:1; fill:none\" points=\"857.083,1739.26 857.083,1720.36 \"/>\n<polyline clip-path=\"url(#clip510)\" style=\"stroke:#000000; stroke-linecap:round; stroke-linejoin:round; stroke-width:4; stroke-opacity:1; fill:none\" points=\"1324.48,1739.26 1324.48,1720.36 \"/>\n<polyline clip-path=\"url(#clip510)\" style=\"stroke:#000000; stroke-linecap:round; stroke-linejoin:round; stroke-width:4; stroke-opacity:1; fill:none\" points=\"1791.88,1739.26 1791.88,1720.36 \"/>\n<polyline clip-path=\"url(#clip510)\" style=\"stroke:#000000; stroke-linecap:round; stroke-linejoin:round; stroke-width:4; stroke-opacity:1; fill:none\" points=\"2259.28,1739.26 2259.28,1720.36 \"/>\n<path clip-path=\"url(#clip510)\" d=\"M350.108 1778.97 Q343.789 1778.97 340.589 1785.21 Q337.429 1791.4 337.429 1803.88 Q337.429 1816.32 340.589 1822.56 Q343.789 1828.75 350.108 1828.75 Q356.468 1828.75 359.628 1822.56 Q362.828 1816.32 362.828 1803.88 Q362.828 1791.4 359.628 1785.21 Q356.468 1778.97 350.108 1778.97 M350.108 1772.49 Q360.276 1772.49 365.623 1780.55 Q371.011 1788.57 371.011 1803.88 Q371.011 1819.15 365.623 1827.21 Q360.276 1835.23 350.108 1835.23 Q339.941 1835.23 334.553 1827.21 Q329.206 1819.15 329.206 1803.88 Q329.206 1788.57 334.553 1780.55 Q339.941 1772.49 350.108 1772.49 Z\" fill=\"#000000\" fill-rule=\"nonzero\" fill-opacity=\"1\" /><path clip-path=\"url(#clip510)\" d=\"M385.392 1823.77 L393.939 1823.77 L393.939 1834.06 L385.392 1834.06 L385.392 1823.77 Z\" fill=\"#000000\" fill-rule=\"nonzero\" fill-opacity=\"1\" /><path clip-path=\"url(#clip510)\" d=\"M429.263 1778.97 Q422.944 1778.97 419.743 1785.21 Q416.584 1791.4 416.584 1803.88 Q416.584 1816.32 419.743 1822.56 Q422.944 1828.75 429.263 1828.75 Q435.623 1828.75 438.783 1822.56 Q441.983 1816.32 441.983 1803.88 Q441.983 1791.4 438.783 1785.21 Q435.623 1778.97 429.263 1778.97 M429.263 1772.49 Q439.431 1772.49 444.778 1780.55 Q450.166 1788.57 450.166 1803.88 Q450.166 1819.15 444.778 1827.21 Q439.431 1835.23 429.263 1835.23 Q419.095 1835.23 413.708 1827.21 Q408.36 1819.15 408.36 1803.88 Q408.36 1788.57 413.708 1780.55 Q419.095 1772.49 429.263 1772.49 Z\" fill=\"#000000\" fill-rule=\"nonzero\" fill-opacity=\"1\" /><path clip-path=\"url(#clip510)\" d=\"M807.622 1827.17 L836.181 1827.17 L836.181 1834.06 L797.778 1834.06 L797.778 1827.17 Q802.437 1822.35 810.457 1814.25 Q818.519 1806.11 820.585 1803.76 Q824.514 1799.34 826.053 1796.31 Q827.633 1793.23 827.633 1790.27 Q827.633 1785.45 824.231 1782.41 Q820.868 1779.37 815.44 1779.37 Q811.592 1779.37 807.298 1780.71 Q803.044 1782.05 798.183 1784.76 L798.183 1776.5 Q803.125 1774.51 807.419 1773.5 Q811.713 1772.49 815.278 1772.49 Q824.676 1772.49 830.266 1777.19 Q835.857 1781.88 835.857 1789.74 Q835.857 1793.47 834.439 1796.83 Q833.061 1800.15 829.375 1804.69 Q828.362 1805.87 822.934 1811.5 Q817.506 1817.09 807.622 1827.17 Z\" fill=\"#000000\" fill-rule=\"nonzero\" fill-opacity=\"1\" /><path clip-path=\"url(#clip510)\" d=\"M853.357 1823.77 L861.904 1823.77 L861.904 1834.06 L853.357 1834.06 L853.357 1823.77 Z\" fill=\"#000000\" fill-rule=\"nonzero\" fill-opacity=\"1\" /><path clip-path=\"url(#clip510)\" d=\"M879.809 1773.58 L911.933 1773.58 L911.933 1780.47 L887.303 1780.47 L887.303 1795.29 Q889.085 1794.69 890.868 1794.4 Q892.65 1794.08 894.433 1794.08 Q904.56 1794.08 910.474 1799.63 Q916.389 1805.18 916.389 1814.66 Q916.389 1824.42 910.312 1829.85 Q904.236 1835.23 893.177 1835.23 Q889.369 1835.23 885.399 1834.59 Q881.47 1833.94 877.257 1832.64 L877.257 1824.42 Q880.903 1826.4 884.792 1827.38 Q888.68 1828.35 893.015 1828.35 Q900.023 1828.35 904.114 1824.66 Q908.206 1820.98 908.206 1814.66 Q908.206 1808.34 904.114 1804.65 Q900.023 1800.96 893.015 1800.96 Q889.734 1800.96 886.452 1801.69 Q883.212 1802.42 879.809 1803.96 L879.809 1773.58 Z\" fill=\"#000000\" fill-rule=\"nonzero\" fill-opacity=\"1\" /><path clip-path=\"url(#clip510)\" d=\"M1267.02 1773.58 L1299.14 1773.58 L1299.14 1780.47 L1274.51 1780.47 L1274.51 1795.29 Q1276.3 1794.69 1278.08 1794.4 Q1279.86 1794.08 1281.64 1794.08 Q1291.77 1794.08 1297.68 1799.63 Q1303.6 1805.18 1303.6 1814.66 Q1303.6 1824.42 1297.52 1829.85 Q1291.45 1835.23 1280.39 1835.23 Q1276.58 1835.23 1272.61 1834.59 Q1268.68 1833.94 1264.47 1832.64 L1264.47 1824.42 Q1268.11 1826.4 1272 1827.38 Q1275.89 1828.35 1280.22 1828.35 Q1287.23 1828.35 1291.32 1824.66 Q1295.42 1820.98 1295.42 1814.66 Q1295.42 1808.34 1291.32 1804.65 Q1287.23 1800.96 1280.22 1800.96 Q1276.94 1800.96 1273.66 1801.69 Q1270.42 1802.42 1267.02 1803.96 L1267.02 1773.58 Z\" fill=\"#000000\" fill-rule=\"nonzero\" fill-opacity=\"1\" /><path clip-path=\"url(#clip510)\" d=\"M1319.72 1823.77 L1328.27 1823.77 L1328.27 1834.06 L1319.72 1834.06 L1319.72 1823.77 Z\" fill=\"#000000\" fill-rule=\"nonzero\" fill-opacity=\"1\" /><path clip-path=\"url(#clip510)\" d=\"M1363.59 1778.97 Q1357.27 1778.97 1354.07 1785.21 Q1350.91 1791.4 1350.91 1803.88 Q1350.91 1816.32 1354.07 1822.56 Q1357.27 1828.75 1363.59 1828.75 Q1369.95 1828.75 1373.11 1822.56 Q1376.31 1816.32 1376.31 1803.88 Q1376.31 1791.4 1373.11 1785.21 Q1369.95 1778.97 1363.59 1778.97 M1363.59 1772.49 Q1373.76 1772.49 1379.11 1780.55 Q1384.5 1788.57 1384.5 1803.88 Q1384.5 1819.15 1379.11 1827.21 Q1373.76 1835.23 1363.59 1835.23 Q1353.42 1835.23 1348.04 1827.21 Q1342.69 1819.15 1342.69 1803.88 Q1342.69 1788.57 1348.04 1780.55 Q1353.42 1772.49 1363.59 1772.49 Z\" fill=\"#000000\" fill-rule=\"nonzero\" fill-opacity=\"1\" /><path clip-path=\"url(#clip510)\" d=\"M1732.94 1773.58 L1771.83 1773.58 L1771.83 1777.06 L1749.87 1834.06 L1741.32 1834.06 L1761.98 1780.47 L1732.94 1780.47 L1732.94 1773.58 Z\" fill=\"#000000\" fill-rule=\"nonzero\" fill-opacity=\"1\" /><path clip-path=\"url(#clip510)\" d=\"M1787.79 1823.77 L1796.33 1823.77 L1796.33 1834.06 L1787.79 1834.06 L1787.79 1823.77 Z\" fill=\"#000000\" fill-rule=\"nonzero\" fill-opacity=\"1\" /><path clip-path=\"url(#clip510)\" d=\"M1814.24 1773.58 L1846.36 1773.58 L1846.36 1780.47 L1821.73 1780.47 L1821.73 1795.29 Q1823.52 1794.69 1825.3 1794.4 Q1827.08 1794.08 1828.86 1794.08 Q1838.99 1794.08 1844.91 1799.63 Q1850.82 1805.18 1850.82 1814.66 Q1850.82 1824.42 1844.74 1829.85 Q1838.67 1835.23 1827.61 1835.23 Q1823.8 1835.23 1819.83 1834.59 Q1815.9 1833.94 1811.69 1832.64 L1811.69 1824.42 Q1815.33 1826.4 1819.22 1827.38 Q1823.11 1828.35 1827.45 1828.35 Q1834.45 1828.35 1838.55 1824.66 Q1842.64 1820.98 1842.64 1814.66 Q1842.64 1808.34 1838.55 1804.65 Q1834.45 1800.96 1827.45 1800.96 Q1824.16 1800.96 1820.88 1801.69 Q1817.64 1802.42 1814.24 1803.96 L1814.24 1773.58 Z\" fill=\"#000000\" fill-rule=\"nonzero\" fill-opacity=\"1\" /><path clip-path=\"url(#clip510)\" d=\"M2175.4 1827.17 L2188.77 1827.17 L2188.77 1781.03 L2174.23 1783.95 L2174.23 1776.5 L2188.69 1773.58 L2196.87 1773.58 L2196.87 1827.17 L2210.24 1827.17 L2210.24 1834.06 L2175.4 1834.06 L2175.4 1827.17 Z\" fill=\"#000000\" fill-rule=\"nonzero\" fill-opacity=\"1\" /><path clip-path=\"url(#clip510)\" d=\"M2244.27 1778.97 Q2237.95 1778.97 2234.75 1785.21 Q2231.59 1791.4 2231.59 1803.88 Q2231.59 1816.32 2234.75 1822.56 Q2237.95 1828.75 2244.27 1828.75 Q2250.63 1828.75 2253.79 1822.56 Q2256.99 1816.32 2256.99 1803.88 Q2256.99 1791.4 2253.79 1785.21 Q2250.63 1778.97 2244.27 1778.97 M2244.27 1772.49 Q2254.44 1772.49 2259.78 1780.55 Q2265.17 1788.57 2265.17 1803.88 Q2265.17 1819.15 2259.78 1827.21 Q2254.44 1835.23 2244.27 1835.23 Q2234.1 1835.23 2228.71 1827.21 Q2223.37 1819.15 2223.37 1803.88 Q2223.37 1788.57 2228.71 1780.55 Q2234.1 1772.49 2244.27 1772.49 Z\" fill=\"#000000\" fill-rule=\"nonzero\" fill-opacity=\"1\" /><path clip-path=\"url(#clip510)\" d=\"M2279.55 1823.77 L2288.1 1823.77 L2288.1 1834.06 L2279.55 1834.06 L2279.55 1823.77 Z\" fill=\"#000000\" fill-rule=\"nonzero\" fill-opacity=\"1\" /><path clip-path=\"url(#clip510)\" d=\"M2323.42 1778.97 Q2317.1 1778.97 2313.9 1785.21 Q2310.74 1791.4 2310.74 1803.88 Q2310.74 1816.32 2313.9 1822.56 Q2317.1 1828.75 2323.42 1828.75 Q2329.78 1828.75 2332.94 1822.56 Q2336.14 1816.32 2336.14 1803.88 Q2336.14 1791.4 2332.94 1785.21 Q2329.78 1778.97 2323.42 1778.97 M2323.42 1772.49 Q2333.59 1772.49 2338.94 1780.55 Q2344.33 1788.57 2344.33 1803.88 Q2344.33 1819.15 2338.94 1827.21 Q2333.59 1835.23 2323.42 1835.23 Q2313.25 1835.23 2307.87 1827.21 Q2302.52 1819.15 2302.52 1803.88 Q2302.52 1788.57 2307.87 1780.55 Q2313.25 1772.49 2323.42 1772.49 Z\" fill=\"#000000\" fill-rule=\"nonzero\" fill-opacity=\"1\" /><path clip-path=\"url(#clip510)\" d=\"M1223.48 1891.84 Q1223.48 1894.47 1221.84 1895.96 Q1220.2 1897.42 1218.33 1897.42 Q1216.55 1897.42 1215.61 1896.39 Q1214.67 1895.36 1214.67 1894.04 Q1214.67 1892.26 1215.98 1890.72 Q1217.3 1889.17 1219.26 1888.84 Q1217.34 1887.63 1214.48 1887.63 Q1212.61 1887.63 1210.97 1888.61 Q1209.38 1889.59 1208.4 1890.86 Q1207.46 1892.12 1206.62 1893.95 Q1205.82 1895.73 1205.49 1896.81 Q1205.21 1897.84 1204.98 1898.96 L1201.7 1912.08 Q1200.1 1918.31 1200.1 1920.51 Q1200.1 1923.23 1201.42 1925.06 Q1202.73 1926.84 1205.35 1926.84 Q1206.38 1926.84 1207.55 1926.55 Q1208.72 1926.23 1210.22 1925.38 Q1211.77 1924.49 1213.13 1923.18 Q1214.53 1921.82 1215.89 1919.53 Q1217.25 1917.23 1218.14 1914.28 Q1218.42 1913.25 1219.36 1913.25 Q1220.53 1913.25 1220.53 1914.19 Q1220.53 1914.98 1219.87 1916.67 Q1219.26 1918.31 1217.9 1920.46 Q1216.59 1922.57 1214.86 1924.49 Q1213.13 1926.37 1210.55 1927.68 Q1207.97 1928.99 1205.16 1928.99 Q1201.13 1928.99 1198.46 1926.84 Q1195.79 1924.68 1194.81 1921.68 Q1194.58 1922.1 1194.25 1922.67 Q1193.92 1923.23 1192.94 1924.49 Q1192 1925.71 1190.92 1926.65 Q1189.84 1927.54 1188.16 1928.24 Q1186.52 1928.99 1184.74 1928.99 Q1182.49 1928.99 1180.48 1928.33 Q1178.51 1927.68 1177.1 1926.18 Q1175.7 1924.68 1175.7 1922.62 Q1175.7 1920.32 1177.24 1918.73 Q1178.84 1917.09 1180.99 1917.09 Q1182.35 1917.09 1183.43 1917.89 Q1184.55 1918.68 1184.55 1920.42 Q1184.55 1922.34 1183.24 1923.79 Q1181.93 1925.24 1180.05 1925.62 Q1181.97 1926.84 1184.83 1926.84 Q1187.92 1926.84 1190.36 1924.12 Q1192.8 1921.4 1193.97 1916.86 Q1196.87 1905.94 1198 1901.07 Q1199.12 1896.15 1199.12 1894.04 Q1199.12 1892.08 1198.6 1890.72 Q1198.09 1889.36 1197.2 1888.75 Q1196.36 1888.09 1195.56 1887.86 Q1194.81 1887.63 1193.97 1887.63 Q1192.56 1887.63 1190.97 1888.19 Q1189.42 1888.75 1187.55 1890.06 Q1185.72 1891.33 1183.99 1893.95 Q1182.26 1896.57 1181.08 1900.18 Q1180.85 1901.26 1179.82 1901.26 Q1178.7 1901.21 1178.7 1900.27 Q1178.7 1899.48 1179.3 1897.84 Q1179.96 1896.15 1181.27 1894.04 Q1182.63 1891.94 1184.36 1890.06 Q1186.14 1888.14 1188.72 1886.83 Q1191.34 1885.52 1194.15 1885.52 Q1195.42 1885.52 1196.64 1885.8 Q1197.9 1886.03 1199.4 1886.74 Q1200.95 1887.44 1202.31 1888.98 Q1203.66 1890.53 1204.51 1892.78 Q1205.07 1891.7 1205.82 1890.67 Q1206.62 1889.64 1207.83 1888.38 Q1209.1 1887.06 1210.83 1886.31 Q1212.61 1885.52 1214.58 1885.52 Q1216.5 1885.52 1218.37 1886.03 Q1220.25 1886.5 1221.84 1888.05 Q1223.48 1889.55 1223.48 1891.84 Z\" fill=\"#000000\" fill-rule=\"nonzero\" fill-opacity=\"1\" /><path clip-path=\"url(#clip510)\" d=\"M1289.56 1855.97 Q1283.36 1866.62 1280.35 1877.03 Q1277.34 1887.45 1277.34 1898.14 Q1277.34 1908.84 1280.35 1919.35 Q1283.4 1929.81 1289.56 1940.41 L1282.15 1940.41 Q1275.21 1929.53 1271.74 1919.02 Q1268.31 1908.51 1268.31 1898.14 Q1268.31 1887.82 1271.74 1877.36 Q1275.16 1866.89 1282.15 1855.97 L1289.56 1855.97 Z\" fill=\"#000000\" fill-rule=\"nonzero\" fill-opacity=\"1\" /><path clip-path=\"url(#clip510)\" d=\"M1305.77 1855.88 L1314.33 1855.88 L1314.33 1898.42 L1339.75 1876.06 L1350.63 1876.06 L1323.13 1900.32 L1351.78 1927.91 L1340.67 1927.91 L1314.33 1902.59 L1314.33 1927.91 L1305.77 1927.91 L1305.77 1855.88 Z\" fill=\"#000000\" fill-rule=\"nonzero\" fill-opacity=\"1\" /><path clip-path=\"url(#clip510)\" d=\"M1401.37 1886.01 Q1404.56 1880.27 1409.01 1877.54 Q1413.45 1874.81 1419.47 1874.81 Q1427.57 1874.81 1431.97 1880.51 Q1436.37 1886.15 1436.37 1896.62 L1436.37 1927.91 L1427.8 1927.91 L1427.8 1896.89 Q1427.8 1889.44 1425.16 1885.83 Q1422.52 1882.22 1417.11 1882.22 Q1410.49 1882.22 1406.64 1886.62 Q1402.8 1891.01 1402.8 1898.61 L1402.8 1927.91 L1394.24 1927.91 L1394.24 1896.89 Q1394.24 1889.39 1391.6 1885.83 Q1388.96 1882.22 1383.45 1882.22 Q1376.92 1882.22 1373.08 1886.66 Q1369.24 1891.06 1369.24 1898.61 L1369.24 1927.91 L1360.67 1927.91 L1360.67 1876.06 L1369.24 1876.06 L1369.24 1884.12 Q1372.15 1879.35 1376.23 1877.08 Q1380.3 1874.81 1385.9 1874.81 Q1391.55 1874.81 1395.49 1877.68 Q1399.47 1880.55 1401.37 1886.01 Z\" fill=\"#000000\" fill-rule=\"nonzero\" fill-opacity=\"1\" /><path clip-path=\"url(#clip510)\" d=\"M1452.01 1855.97 L1459.42 1855.97 Q1466.37 1866.89 1469.79 1877.36 Q1473.26 1887.82 1473.26 1898.14 Q1473.26 1908.51 1469.79 1919.02 Q1466.37 1929.53 1459.42 1940.41 L1452.01 1940.41 Q1458.17 1929.81 1461.18 1919.35 Q1464.24 1908.84 1464.24 1898.14 Q1464.24 1887.45 1461.18 1877.03 Q1458.17 1866.62 1452.01 1855.97 Z\" fill=\"#000000\" fill-rule=\"nonzero\" fill-opacity=\"1\" /><polyline clip-path=\"url(#clip512)\" style=\"stroke:#000000; stroke-linecap:round; stroke-linejoin:round; stroke-width:2; stroke-opacity:0.1; fill:none\" points=\"296.206,1739.26 2352.76,1739.26 \"/>\n<polyline clip-path=\"url(#clip512)\" style=\"stroke:#000000; stroke-linecap:round; stroke-linejoin:round; stroke-width:2; stroke-opacity:0.1; fill:none\" points=\"296.206,1316.26 2352.76,1316.26 \"/>\n<polyline clip-path=\"url(#clip512)\" style=\"stroke:#000000; stroke-linecap:round; stroke-linejoin:round; stroke-width:2; stroke-opacity:0.1; fill:none\" points=\"296.206,893.252 2352.76,893.252 \"/>\n<polyline clip-path=\"url(#clip512)\" style=\"stroke:#000000; stroke-linecap:round; stroke-linejoin:round; stroke-width:2; stroke-opacity:0.1; fill:none\" points=\"296.206,470.248 2352.76,470.248 \"/>\n<polyline clip-path=\"url(#clip512)\" style=\"stroke:#000000; stroke-linecap:round; stroke-linejoin:round; stroke-width:2; stroke-opacity:0.1; fill:none\" points=\"296.206,47.2441 2352.76,47.2441 \"/>\n<polyline clip-path=\"url(#clip510)\" style=\"stroke:#000000; stroke-linecap:round; stroke-linejoin:round; stroke-width:4; stroke-opacity:1; fill:none\" points=\"296.206,1739.26 296.206,47.2441 \"/>\n<polyline clip-path=\"url(#clip510)\" style=\"stroke:#000000; stroke-linecap:round; stroke-linejoin:round; stroke-width:4; stroke-opacity:1; fill:none\" points=\"296.206,1739.26 315.104,1739.26 \"/>\n<polyline clip-path=\"url(#clip510)\" style=\"stroke:#000000; stroke-linecap:round; stroke-linejoin:round; stroke-width:4; stroke-opacity:1; fill:none\" points=\"296.206,1316.26 315.104,1316.26 \"/>\n<polyline clip-path=\"url(#clip510)\" style=\"stroke:#000000; stroke-linecap:round; stroke-linejoin:round; stroke-width:4; stroke-opacity:1; fill:none\" points=\"296.206,893.252 315.104,893.252 \"/>\n<polyline clip-path=\"url(#clip510)\" style=\"stroke:#000000; stroke-linecap:round; stroke-linejoin:round; stroke-width:4; stroke-opacity:1; fill:none\" points=\"296.206,470.248 315.104,470.248 \"/>\n<polyline clip-path=\"url(#clip510)\" style=\"stroke:#000000; stroke-linecap:round; stroke-linejoin:round; stroke-width:4; stroke-opacity:1; fill:none\" points=\"296.206,47.2441 315.104,47.2441 \"/>\n<path clip-path=\"url(#clip510)\" d=\"M239.303 1714.41 Q232.984 1714.41 229.784 1720.65 Q226.624 1726.84 226.624 1739.32 Q226.624 1751.76 229.784 1758 Q232.984 1764.19 239.303 1764.19 Q245.663 1764.19 248.823 1758 Q252.023 1751.76 252.023 1739.32 Q252.023 1726.84 248.823 1720.65 Q245.663 1714.41 239.303 1714.41 M239.303 1707.93 Q249.471 1707.93 254.818 1715.99 Q260.206 1724.01 260.206 1739.32 Q260.206 1754.59 254.818 1762.65 Q249.471 1770.67 239.303 1770.67 Q229.136 1770.67 223.748 1762.65 Q218.401 1754.59 218.401 1739.32 Q218.401 1724.01 223.748 1715.99 Q229.136 1707.93 239.303 1707.93 Z\" fill=\"#000000\" fill-rule=\"nonzero\" fill-opacity=\"1\" /><path clip-path=\"url(#clip510)\" d=\"M231.647 1339.61 L260.206 1339.61 L260.206 1346.5 L221.804 1346.5 L221.804 1339.61 Q226.462 1334.79 234.483 1326.69 Q242.544 1318.54 244.61 1316.2 Q248.54 1311.78 250.079 1308.74 Q251.659 1305.66 251.659 1302.71 Q251.659 1297.89 248.256 1294.85 Q244.894 1291.81 239.465 1291.81 Q235.617 1291.81 231.323 1293.15 Q227.07 1294.48 222.209 1297.2 L222.209 1288.93 Q227.151 1286.95 231.445 1285.93 Q235.739 1284.92 239.303 1284.92 Q248.702 1284.92 254.292 1289.62 Q259.882 1294.32 259.882 1302.18 Q259.882 1305.91 258.464 1309.27 Q257.087 1312.59 253.401 1317.13 Q252.388 1318.3 246.96 1323.93 Q241.531 1329.52 231.647 1339.61 Z\" fill=\"#000000\" fill-rule=\"nonzero\" fill-opacity=\"1\" /><path clip-path=\"url(#clip510)\" d=\"M243.435 870.142 L222.776 902.427 L243.435 902.427 L243.435 870.142 M241.288 863.012 L251.578 863.012 L251.578 902.427 L260.206 902.427 L260.206 909.233 L251.578 909.233 L251.578 923.492 L243.435 923.492 L243.435 909.233 L216.132 909.233 L216.132 901.334 L241.288 863.012 Z\" fill=\"#000000\" fill-rule=\"nonzero\" fill-opacity=\"1\" /><path clip-path=\"url(#clip510)\" d=\"M240.033 466.987 Q234.523 466.987 231.283 470.754 Q228.082 474.522 228.082 481.084 Q228.082 487.606 231.283 491.414 Q234.523 495.181 240.033 495.181 Q245.542 495.181 248.742 491.414 Q251.983 487.606 251.983 481.084 Q251.983 474.522 248.742 470.754 Q245.542 466.987 240.033 466.987 M256.277 441.345 L256.277 448.798 Q253.198 447.34 250.038 446.57 Q246.919 445.801 243.84 445.801 Q235.739 445.801 231.445 451.27 Q227.191 456.738 226.584 467.797 Q228.974 464.273 232.579 462.41 Q236.184 460.506 240.519 460.506 Q249.633 460.506 254.899 466.055 Q260.206 471.565 260.206 481.084 Q260.206 490.401 254.697 496.032 Q249.188 501.663 240.033 501.663 Q229.541 501.663 223.991 493.642 Q218.441 485.581 218.441 470.309 Q218.441 455.969 225.247 447.462 Q232.052 438.914 243.516 438.914 Q246.595 438.914 249.714 439.522 Q252.874 440.13 256.277 441.345 Z\" fill=\"#000000\" fill-rule=\"nonzero\" fill-opacity=\"1\" /><path clip-path=\"url(#clip510)\" d=\"M239.465 48.7632 Q233.632 48.7632 230.27 51.8824 Q226.948 55.0016 226.948 60.4703 Q226.948 65.939 230.27 69.0582 Q233.632 72.1774 239.465 72.1774 Q245.299 72.1774 248.661 69.0582 Q252.023 65.8985 252.023 60.4703 Q252.023 55.0016 248.661 51.8824 Q245.339 48.7632 239.465 48.7632 M231.283 45.2794 Q226.016 43.9831 223.059 40.3778 Q220.143 36.7725 220.143 31.5873 Q220.143 24.3362 225.287 20.1233 Q230.472 15.9104 239.465 15.9104 Q248.499 15.9104 253.644 20.1233 Q258.788 24.3362 258.788 31.5873 Q258.788 36.7725 255.831 40.3778 Q252.914 43.9831 247.689 45.2794 Q253.603 46.6567 256.884 50.6671 Q260.206 54.6775 260.206 60.4703 Q260.206 69.2608 254.818 73.9598 Q249.471 78.6589 239.465 78.6589 Q229.46 78.6589 224.072 73.9598 Q218.725 69.2608 218.725 60.4703 Q218.725 54.6775 222.047 50.6671 Q225.368 46.6567 231.283 45.2794 M228.285 32.357 Q228.285 37.0561 231.202 39.6892 Q234.159 42.3222 239.465 42.3222 Q244.732 42.3222 247.689 39.6892 Q250.686 37.0561 250.686 32.357 Q250.686 27.658 247.689 25.0249 Q244.732 22.3918 239.465 22.3918 Q234.159 22.3918 231.202 25.0249 Q228.285 27.658 228.285 32.357 Z\" fill=\"#000000\" fill-rule=\"nonzero\" fill-opacity=\"1\" /><path clip-path=\"url(#clip510)\" d=\"M111.17 993.87 Q111.825 993.87 113.371 994.292 L150.004 1003.47 Q158.155 1005.49 163.87 1012.05 Q169.585 1018.56 169.585 1025.96 Q169.585 1030.41 167.196 1033.27 Q164.854 1036.12 161.247 1036.12 Q158.061 1036.12 156.515 1034.44 Q155.016 1032.75 155.016 1030.74 Q155.016 1030.08 155.204 1029.38 Q155.391 1028.68 156.187 1027.93 Q156.984 1027.18 158.342 1027.18 Q160.544 1027.18 162.277 1029.1 Q163.074 1030.03 163.261 1030.92 Q163.448 1031.77 163.448 1033.22 Q164.76 1032.66 165.65 1031.63 Q166.54 1030.6 166.868 1029.43 Q167.243 1028.25 167.337 1027.5 Q167.477 1026.71 167.477 1025.96 Q167.477 1019.96 161.434 1015.37 Q159.607 1014.01 157.78 1013.03 Q156 1012 153.798 1011.25 Q151.644 1010.5 150.472 1010.17 Q149.301 1009.8 146.631 1009.14 Q150.988 1013.5 150.988 1018.84 Q150.988 1021.09 150.379 1023.1 Q149.77 1025.07 148.505 1026.8 Q147.193 1028.54 144.898 1029.57 Q142.602 1030.55 139.558 1030.55 Q136.325 1030.55 131.922 1029.28 Q127.518 1028.02 119.414 1024.98 Q114.87 1023.34 112.669 1023.34 Q111.591 1023.34 110.935 1023.57 Q110.233 1023.8 109.998 1024.27 Q109.717 1024.74 109.671 1025.02 Q109.624 1025.26 109.624 1025.72 Q109.624 1028.49 112.434 1031.06 Q115.245 1033.64 121.522 1035.42 Q122.693 1035.8 122.974 1036.03 Q123.256 1036.26 123.256 1036.97 Q123.209 1038.14 122.272 1038.14 Q121.897 1038.14 120.445 1037.72 Q118.946 1037.3 116.744 1036.31 Q114.496 1035.28 112.481 1033.88 Q110.42 1032.47 108.968 1030.27 Q107.516 1028.02 107.516 1025.44 Q107.516 1021.93 109.811 1019.78 Q112.06 1017.57 115.386 1017.57 Q116.744 1017.57 117.962 1017.95 Q119.133 1018.28 122.272 1019.49 Q134.92 1024.41 141.103 1024.41 Q142.602 1024.41 143.867 1024.18 Q145.085 1023.9 146.303 1023.29 Q147.474 1022.68 148.177 1021.46 Q148.833 1020.2 148.833 1018.46 Q148.833 1016.26 147.802 1014.2 Q146.725 1012.09 145.273 1010.78 Q143.82 1009.42 142.602 1008.63 Q141.338 1007.78 140.682 1007.6 L123.443 1003.29 L115.76 1001.37 Q111.591 1000.48 110.561 1000.05 Q109.577 999.491 109.062 998.508 Q108.546 997.524 108.546 996.681 Q108.546 995.51 109.249 994.713 Q109.952 993.87 111.17 993.87 Z\" fill=\"#000000\" fill-rule=\"nonzero\" fill-opacity=\"1\" /><path clip-path=\"url(#clip510)\" d=\"M77.9662 932.068 Q88.6143 938.272 99.0309 941.281 Q109.448 944.29 120.142 944.29 Q130.836 944.29 141.346 941.281 Q151.808 938.226 162.41 932.068 L162.41 939.476 Q151.531 946.42 141.021 949.892 Q130.512 953.318 120.142 953.318 Q109.818 953.318 99.355 949.892 Q88.8921 946.466 77.9662 939.476 L77.9662 932.068 Z\" fill=\"#000000\" fill-rule=\"nonzero\" fill-opacity=\"1\" /><path clip-path=\"url(#clip510)\" d=\"M77.8736 915.865 L77.8736 907.3 L120.42 907.3 L98.0587 881.883 L98.0587 871.004 L122.318 898.504 L149.91 869.846 L149.91 880.957 L124.586 907.3 L149.91 907.3 L149.91 915.865 L77.8736 915.865 Z\" fill=\"#000000\" fill-rule=\"nonzero\" fill-opacity=\"1\" /><path clip-path=\"url(#clip510)\" d=\"M108.012 820.263 Q102.272 817.069 99.5402 812.624 Q96.8087 808.18 96.8087 802.161 Q96.8087 794.06 102.503 789.662 Q108.151 785.263 118.614 785.263 L149.91 785.263 L149.91 793.828 L118.892 793.828 Q111.438 793.828 107.827 796.467 Q104.216 799.106 104.216 804.523 Q104.216 811.143 108.614 814.986 Q113.012 818.828 120.605 818.828 L149.91 818.828 L149.91 827.393 L118.892 827.393 Q111.392 827.393 107.827 830.032 Q104.216 832.671 104.216 838.18 Q104.216 844.708 108.661 848.55 Q113.059 852.393 120.605 852.393 L149.91 852.393 L149.91 860.957 L98.0587 860.957 L98.0587 852.393 L106.114 852.393 Q101.346 849.476 99.0772 845.402 Q96.8087 841.328 96.8087 835.726 Q96.8087 830.078 99.6791 826.143 Q102.549 822.161 108.012 820.263 Z\" fill=\"#000000\" fill-rule=\"nonzero\" fill-opacity=\"1\" /><path clip-path=\"url(#clip510)\" d=\"M77.9662 769.615 L77.9662 762.208 Q88.8921 755.264 99.355 751.838 Q109.818 748.365 120.142 748.365 Q130.512 748.365 141.021 751.838 Q151.531 755.264 162.41 762.208 L162.41 769.615 Q151.808 763.458 141.346 760.449 Q130.836 757.393 120.142 757.393 Q109.448 757.393 99.0309 760.449 Q88.6143 763.458 77.9662 769.615 Z\" fill=\"#000000\" fill-rule=\"nonzero\" fill-opacity=\"1\" /><circle clip-path=\"url(#clip512)\" cx=\"389.686\" cy=\"258.746\" r=\"21.6\" fill=\"#ff0000\" fill-rule=\"evenodd\" fill-opacity=\"1\" stroke=\"#000000\" stroke-opacity=\"1\" stroke-width=\"4\"/>\n<circle clip-path=\"url(#clip512)\" cx=\"763.604\" cy=\"681.75\" r=\"21.6\" fill=\"#ff0000\" fill-rule=\"evenodd\" fill-opacity=\"1\" stroke=\"#000000\" stroke-opacity=\"1\" stroke-width=\"4\"/>\n<circle clip-path=\"url(#clip512)\" cx=\"950.563\" cy=\"681.75\" r=\"21.6\" fill=\"#ff0000\" fill-rule=\"evenodd\" fill-opacity=\"1\" stroke=\"#000000\" stroke-opacity=\"1\" stroke-width=\"4\"/>\n<circle clip-path=\"url(#clip512)\" cx=\"576.645\" cy=\"1422.01\" r=\"21.6\" fill=\"#000000\" fill-rule=\"evenodd\" fill-opacity=\"1\" stroke=\"none\"/>\n<circle clip-path=\"url(#clip512)\" cx=\"950.563\" cy=\"258.746\" r=\"21.6\" fill=\"#000000\" fill-rule=\"evenodd\" fill-opacity=\"1\" stroke=\"none\"/>\n<circle clip-path=\"url(#clip512)\" cx=\"1324.48\" cy=\"1104.75\" r=\"21.6\" fill=\"#000000\" fill-rule=\"evenodd\" fill-opacity=\"1\" stroke=\"none\"/>\n<circle clip-path=\"url(#clip512)\" cx=\"1791.88\" cy=\"470.248\" r=\"21.6\" fill=\"#000000\" fill-rule=\"evenodd\" fill-opacity=\"1\" stroke=\"none\"/>\n<circle clip-path=\"url(#clip512)\" cx=\"2259.28\" cy=\"681.75\" r=\"21.6\" fill=\"#000000\" fill-rule=\"evenodd\" fill-opacity=\"1\" stroke=\"none\"/>\n<polyline clip-path=\"url(#clip512)\" style=\"stroke:#0000ff; stroke-linecap:round; stroke-linejoin:round; stroke-width:8; stroke-opacity:1; fill:none\" points=\"389.686,100.12 2259.28,100.12 \"/>\n<polyline clip-path=\"url(#clip512)\" style=\"stroke:#0000ff; stroke-linecap:round; stroke-linejoin:round; stroke-width:8; stroke-opacity:1; fill:none\" points=\"2223.28,82.1196 2259.28,100.12 2223.28,118.12 \"/>\n<polyline clip-path=\"url(#clip512)\" style=\"stroke:#0000ff; stroke-linecap:round; stroke-linejoin:round; stroke-width:8; stroke-opacity:1; fill:none\" points=\"2259.28,100.12 389.686,100.12 \"/>\n<path clip-path=\"url(#clip510)\" d=\"M1663.09 1682.86 L2284.2 1682.86 L2284.2 1371.82 L1663.09 1371.82  Z\" fill=\"#ffffff\" fill-rule=\"evenodd\" fill-opacity=\"1\"/>\n<polyline clip-path=\"url(#clip510)\" style=\"stroke:#000000; stroke-linecap:round; stroke-linejoin:round; stroke-width:4; stroke-opacity:1; fill:none\" points=\"1663.09,1682.86 2284.2,1682.86 2284.2,1371.82 1663.09,1371.82 1663.09,1682.86 \"/>\n<circle clip-path=\"url(#clip510)\" cx=\"1754.49\" cy=\"1475.5\" r=\"42.5354\" fill=\"#ff0000\" fill-rule=\"evenodd\" fill-opacity=\"1\" stroke=\"#000000\" stroke-opacity=\"1\" stroke-width=\"7.87692\"/>\n<path clip-path=\"url(#clip510)\" d=\"M1890.38 1443.21 L1890.38 1452.33 Q1885.06 1449.78 1880.34 1448.53 Q1875.62 1447.28 1871.22 1447.28 Q1863.58 1447.28 1859.41 1450.24 Q1855.29 1453.21 1855.29 1458.67 Q1855.29 1463.25 1858.02 1465.62 Q1860.8 1467.93 1868.49 1469.37 L1874.13 1470.52 Q1884.6 1472.51 1889.55 1477.56 Q1894.55 1482.56 1894.55 1490.99 Q1894.55 1501.03 1887.79 1506.22 Q1881.08 1511.4 1868.07 1511.4 Q1863.16 1511.4 1857.61 1510.29 Q1852.1 1509.18 1846.17 1507 L1846.17 1497.37 Q1851.87 1500.57 1857.33 1502.19 Q1862.79 1503.81 1868.07 1503.81 Q1876.08 1503.81 1880.43 1500.66 Q1884.78 1497.51 1884.78 1491.68 Q1884.78 1486.59 1881.63 1483.72 Q1878.53 1480.85 1871.4 1479.41 L1865.71 1478.3 Q1855.24 1476.22 1850.57 1471.77 Q1845.89 1467.33 1845.89 1459.41 Q1845.89 1450.24 1852.33 1444.97 Q1858.81 1439.69 1870.15 1439.69 Q1875.01 1439.69 1880.06 1440.57 Q1885.11 1441.45 1890.38 1443.21 Z\" fill=\"#000000\" fill-rule=\"nonzero\" fill-opacity=\"1\" /><path clip-path=\"url(#clip510)\" d=\"M1928.86 1464.18 Q1922 1464.18 1918.02 1469.55 Q1914.04 1474.87 1914.04 1484.18 Q1914.04 1493.49 1917.98 1498.86 Q1921.96 1504.18 1928.86 1504.18 Q1935.66 1504.18 1939.64 1498.81 Q1943.62 1493.44 1943.62 1484.18 Q1943.62 1474.97 1939.64 1469.6 Q1935.66 1464.18 1928.86 1464.18 M1928.86 1456.96 Q1939.97 1456.96 1946.31 1464.18 Q1952.65 1471.4 1952.65 1484.18 Q1952.65 1496.91 1946.31 1504.18 Q1939.97 1511.4 1928.86 1511.4 Q1917.7 1511.4 1911.36 1504.18 Q1905.06 1496.91 1905.06 1484.18 Q1905.06 1471.4 1911.36 1464.18 Q1917.7 1456.96 1928.86 1456.96 Z\" fill=\"#000000\" fill-rule=\"nonzero\" fill-opacity=\"1\" /><path clip-path=\"url(#clip510)\" d=\"M1965.89 1489.6 L1965.89 1458.21 L1974.41 1458.21 L1974.41 1489.27 Q1974.41 1496.63 1977.28 1500.34 Q1980.15 1503.99 1985.89 1503.99 Q1992.79 1503.99 1996.77 1499.6 Q2000.8 1495.2 2000.8 1487.61 L2000.8 1458.21 L2009.32 1458.21 L2009.32 1510.06 L2000.8 1510.06 L2000.8 1502.1 Q1997.7 1506.82 1993.58 1509.13 Q1989.5 1511.4 1984.09 1511.4 Q1975.15 1511.4 1970.52 1505.85 Q1965.89 1500.29 1965.89 1489.6 M1987.33 1456.96 L1987.33 1456.96 Z\" fill=\"#000000\" fill-rule=\"nonzero\" fill-opacity=\"1\" /><path clip-path=\"url(#clip510)\" d=\"M2056.91 1466.17 Q2055.48 1465.34 2053.76 1464.97 Q2052.1 1464.55 2050.06 1464.55 Q2042.84 1464.55 2038.95 1469.27 Q2035.1 1473.95 2035.1 1482.74 L2035.1 1510.06 L2026.54 1510.06 L2026.54 1458.21 L2035.1 1458.21 L2035.1 1466.26 Q2037.79 1461.54 2042.1 1459.27 Q2046.4 1456.96 2052.56 1456.96 Q2053.44 1456.96 2054.5 1457.1 Q2055.57 1457.19 2056.86 1457.42 L2056.91 1466.17 Z\" fill=\"#000000\" fill-rule=\"nonzero\" fill-opacity=\"1\" /><path clip-path=\"url(#clip510)\" d=\"M2101.08 1460.2 L2101.08 1468.16 Q2097.47 1466.17 2093.81 1465.2 Q2090.2 1464.18 2086.49 1464.18 Q2078.21 1464.18 2073.62 1469.46 Q2069.04 1474.69 2069.04 1484.18 Q2069.04 1493.67 2073.62 1498.95 Q2078.21 1504.18 2086.49 1504.18 Q2090.2 1504.18 2093.81 1503.21 Q2097.47 1502.19 2101.08 1500.2 L2101.08 1508.07 Q2097.51 1509.74 2093.67 1510.57 Q2089.87 1511.4 2085.57 1511.4 Q2073.85 1511.4 2066.96 1504.04 Q2060.06 1496.68 2060.06 1484.18 Q2060.06 1471.49 2067 1464.23 Q2073.99 1456.96 2086.12 1456.96 Q2090.06 1456.96 2093.81 1457.79 Q2097.56 1458.58 2101.08 1460.2 Z\" fill=\"#000000\" fill-rule=\"nonzero\" fill-opacity=\"1\" /><path clip-path=\"url(#clip510)\" d=\"M2160.24 1482 L2160.24 1486.17 L2121.08 1486.17 Q2121.63 1494.97 2126.35 1499.6 Q2131.12 1504.18 2139.6 1504.18 Q2144.5 1504.18 2149.09 1502.98 Q2153.72 1501.77 2158.25 1499.36 L2158.25 1507.42 Q2153.67 1509.36 2148.85 1510.38 Q2144.04 1511.4 2139.09 1511.4 Q2126.68 1511.4 2119.41 1504.18 Q2112.19 1496.96 2112.19 1484.64 Q2112.19 1471.91 2119.04 1464.46 Q2125.94 1456.96 2137.6 1456.96 Q2148.07 1456.96 2154.13 1463.72 Q2160.24 1470.43 2160.24 1482 M2151.72 1479.5 Q2151.63 1472.51 2147.79 1468.35 Q2143.99 1464.18 2137.7 1464.18 Q2130.57 1464.18 2126.26 1468.21 Q2122 1472.24 2121.35 1479.55 L2151.72 1479.5 Z\" fill=\"#000000\" fill-rule=\"nonzero\" fill-opacity=\"1\" /><circle clip-path=\"url(#clip510)\" cx=\"1754.49\" cy=\"1579.18\" r=\"42.5354\" fill=\"#000000\" fill-rule=\"evenodd\" fill-opacity=\"1\" stroke=\"none\"/>\n<path clip-path=\"url(#clip510)\" d=\"M1878.67 1581.33 Q1881.68 1582.35 1884.5 1585.68 Q1887.37 1589.02 1890.24 1594.85 L1899.74 1613.74 L1889.69 1613.74 L1880.85 1596.01 Q1877.42 1589.06 1874.18 1586.8 Q1870.99 1584.53 1865.43 1584.53 L1855.24 1584.53 L1855.24 1613.74 L1845.89 1613.74 L1845.89 1544.62 L1867 1544.62 Q1878.86 1544.62 1884.69 1549.57 Q1890.52 1554.53 1890.52 1564.53 Q1890.52 1571.05 1887.47 1575.36 Q1884.46 1579.67 1878.67 1581.33 M1855.24 1552.3 L1855.24 1576.84 L1867 1576.84 Q1873.76 1576.84 1877.19 1573.74 Q1880.66 1570.59 1880.66 1564.53 Q1880.66 1558.46 1877.19 1555.41 Q1873.76 1552.3 1867 1552.3 L1855.24 1552.3 Z\" fill=\"#000000\" fill-rule=\"nonzero\" fill-opacity=\"1\" /><path clip-path=\"url(#clip510)\" d=\"M1951.49 1585.68 L1951.49 1589.85 L1912.33 1589.85 Q1912.88 1598.65 1917.61 1603.28 Q1922.37 1607.86 1930.85 1607.86 Q1935.75 1607.86 1940.34 1606.66 Q1944.97 1605.45 1949.5 1603.04 L1949.5 1611.1 Q1944.92 1613.04 1940.11 1614.06 Q1935.29 1615.08 1930.34 1615.08 Q1917.93 1615.08 1910.66 1607.86 Q1903.44 1600.64 1903.44 1588.32 Q1903.44 1575.59 1910.29 1568.14 Q1917.19 1560.64 1928.86 1560.64 Q1939.32 1560.64 1945.38 1567.4 Q1951.49 1574.11 1951.49 1585.68 M1942.98 1583.18 Q1942.88 1576.19 1939.04 1572.03 Q1935.24 1567.86 1928.95 1567.86 Q1921.82 1567.86 1917.51 1571.89 Q1913.25 1575.92 1912.61 1583.23 L1942.98 1583.18 Z\" fill=\"#000000\" fill-rule=\"nonzero\" fill-opacity=\"1\" /><path clip-path=\"url(#clip510)\" d=\"M2002.79 1563.88 L2002.79 1571.84 Q1999.18 1569.85 1995.52 1568.88 Q1991.91 1567.86 1988.21 1567.86 Q1979.92 1567.86 1975.34 1573.14 Q1970.75 1578.37 1970.75 1587.86 Q1970.75 1597.35 1975.34 1602.63 Q1979.92 1607.86 1988.21 1607.86 Q1991.91 1607.86 1995.52 1606.89 Q1999.18 1605.87 2002.79 1603.88 L2002.79 1611.75 Q1999.23 1613.42 1995.38 1614.25 Q1991.59 1615.08 1987.28 1615.08 Q1975.57 1615.08 1968.67 1607.72 Q1961.77 1600.36 1961.77 1587.86 Q1961.77 1575.17 1968.72 1567.91 Q1975.71 1560.64 1987.84 1560.64 Q1991.77 1560.64 1995.52 1561.47 Q1999.27 1562.26 2002.79 1563.88 Z\" fill=\"#000000\" fill-rule=\"nonzero\" fill-opacity=\"1\" /><path clip-path=\"url(#clip510)\" d=\"M2061.96 1585.68 L2061.96 1589.85 L2022.79 1589.85 Q2023.35 1598.65 2028.07 1603.28 Q2032.84 1607.86 2041.31 1607.86 Q2046.22 1607.86 2050.8 1606.66 Q2055.43 1605.45 2059.97 1603.04 L2059.97 1611.1 Q2055.38 1613.04 2050.57 1614.06 Q2045.75 1615.08 2040.8 1615.08 Q2028.39 1615.08 2021.12 1607.86 Q2013.9 1600.64 2013.9 1588.32 Q2013.9 1575.59 2020.75 1568.14 Q2027.65 1560.64 2039.32 1560.64 Q2049.78 1560.64 2055.85 1567.4 Q2061.96 1574.11 2061.96 1585.68 M2053.44 1583.18 Q2053.35 1576.19 2049.5 1572.03 Q2045.71 1567.86 2039.41 1567.86 Q2032.28 1567.86 2027.98 1571.89 Q2023.72 1575.92 2023.07 1583.23 L2053.44 1583.18 Z\" fill=\"#000000\" fill-rule=\"nonzero\" fill-opacity=\"1\" /><path clip-path=\"url(#clip510)\" d=\"M2084.18 1605.96 L2084.18 1633.46 L2075.61 1633.46 L2075.61 1561.89 L2084.18 1561.89 L2084.18 1569.76 Q2086.86 1565.13 2090.94 1562.91 Q2095.06 1560.64 2100.75 1560.64 Q2110.2 1560.64 2116.08 1568.14 Q2122 1575.64 2122 1587.86 Q2122 1600.08 2116.08 1607.58 Q2110.2 1615.08 2100.75 1615.08 Q2095.06 1615.08 2090.94 1612.86 Q2086.86 1610.59 2084.18 1605.96 M2113.16 1587.86 Q2113.16 1578.46 2109.27 1573.14 Q2105.43 1567.77 2098.67 1567.77 Q2091.91 1567.77 2088.02 1573.14 Q2084.18 1578.46 2084.18 1587.86 Q2084.18 1597.26 2088.02 1602.63 Q2091.91 1607.95 2098.67 1607.95 Q2105.43 1607.95 2109.27 1602.63 Q2113.16 1597.26 2113.16 1587.86 Z\" fill=\"#000000\" fill-rule=\"nonzero\" fill-opacity=\"1\" /><path clip-path=\"url(#clip510)\" d=\"M2144.55 1547.17 L2144.55 1561.89 L2162.09 1561.89 L2162.09 1568.51 L2144.55 1568.51 L2144.55 1596.66 Q2144.55 1603 2146.26 1604.8 Q2148.02 1606.61 2153.35 1606.61 L2162.09 1606.61 L2162.09 1613.74 L2153.35 1613.74 Q2143.48 1613.74 2139.73 1610.08 Q2135.98 1606.38 2135.98 1596.66 L2135.98 1568.51 L2129.73 1568.51 L2129.73 1561.89 L2135.98 1561.89 L2135.98 1547.17 L2144.55 1547.17 Z\" fill=\"#000000\" fill-rule=\"nonzero\" fill-opacity=\"1\" /><path clip-path=\"url(#clip510)\" d=\"M2193.39 1567.86 Q2186.54 1567.86 2182.56 1573.23 Q2178.58 1578.55 2178.58 1587.86 Q2178.58 1597.17 2182.51 1602.54 Q2186.49 1607.86 2193.39 1607.86 Q2200.2 1607.86 2204.18 1602.49 Q2208.16 1597.12 2208.16 1587.86 Q2208.16 1578.65 2204.18 1573.28 Q2200.2 1567.86 2193.39 1567.86 M2193.39 1560.64 Q2204.5 1560.64 2210.84 1567.86 Q2217.19 1575.08 2217.19 1587.86 Q2217.19 1600.59 2210.84 1607.86 Q2204.5 1615.08 2193.39 1615.08 Q2182.23 1615.08 2175.89 1607.86 Q2169.59 1600.59 2169.59 1587.86 Q2169.59 1575.08 2175.89 1567.86 Q2182.23 1560.64 2193.39 1560.64 Z\" fill=\"#000000\" fill-rule=\"nonzero\" fill-opacity=\"1\" /><path clip-path=\"url(#clip510)\" d=\"M2261.35 1569.85 Q2259.92 1569.02 2258.21 1568.65 Q2256.54 1568.23 2254.5 1568.23 Q2247.28 1568.23 2243.39 1572.95 Q2239.55 1577.63 2239.55 1586.42 L2239.55 1613.74 L2230.98 1613.74 L2230.98 1561.89 L2239.55 1561.89 L2239.55 1569.94 Q2242.23 1565.22 2246.54 1562.95 Q2250.84 1560.64 2257 1560.64 Q2257.88 1560.64 2258.95 1560.78 Q2260.01 1560.87 2261.31 1561.1 L2261.35 1569.85 Z\" fill=\"#000000\" fill-rule=\"nonzero\" fill-opacity=\"1\" /><path clip-path=\"url(#clip510)\" d=\"M372.854 218.649 L386.222 218.649 L386.222 172.509 L371.679 175.426 L371.679 167.972 L386.141 165.055 L394.324 165.055 L394.324 218.649 L407.692 218.649 L407.692 225.535 L372.854 225.535 L372.854 218.649 Z\" fill=\"#ff0000\" fill-rule=\"nonzero\" fill-opacity=\"1\" /><path clip-path=\"url(#clip510)\" d=\"M303.888 289.486 Q298.459 298.803 295.826 307.917 Q293.193 317.032 293.193 326.389 Q293.193 335.747 295.826 344.942 Q298.5 354.098 303.888 363.374 L297.406 363.374 Q291.33 353.854 288.292 344.659 Q285.294 335.463 285.294 326.389 Q285.294 317.356 288.292 308.201 Q291.289 299.046 297.406 289.486 L303.888 289.486 Z\" fill=\"#ff0000\" fill-rule=\"nonzero\" fill-opacity=\"1\" /><path clip-path=\"url(#clip510)\" d=\"M336.902 297.344 Q330.583 297.344 327.383 303.583 Q324.223 309.781 324.223 322.257 Q324.223 334.694 327.383 340.932 Q330.583 347.13 336.902 347.13 Q343.262 347.13 346.422 340.932 Q349.622 334.694 349.622 322.257 Q349.622 309.781 346.422 303.583 Q343.262 297.344 336.902 297.344 M336.902 290.863 Q347.07 290.863 352.417 298.924 Q357.805 306.945 357.805 322.257 Q357.805 337.529 352.417 345.591 Q347.07 353.611 336.902 353.611 Q326.735 353.611 321.347 345.591 Q316 337.529 316 322.257 Q316 306.945 321.347 298.924 Q326.735 290.863 336.902 290.863 Z\" fill=\"#ff0000\" fill-rule=\"nonzero\" fill-opacity=\"1\" /><path clip-path=\"url(#clip510)\" d=\"M373.036 342.147 L381.584 342.147 L381.584 349.115 L374.94 362.078 L369.715 362.078 L373.036 349.115 L373.036 342.147 Z\" fill=\"#ff0000\" fill-rule=\"nonzero\" fill-opacity=\"1\" /><path clip-path=\"url(#clip510)\" d=\"M422.863 291.957 L461.751 291.957 L461.751 295.44 L439.795 352.437 L431.248 352.437 L451.908 298.843 L422.863 298.843 L422.863 291.957 Z\" fill=\"#ff0000\" fill-rule=\"nonzero\" fill-opacity=\"1\" /><path clip-path=\"url(#clip510)\" d=\"M475.484 289.486 L481.965 289.486 Q488.042 299.046 491.039 308.201 Q494.077 317.356 494.077 326.389 Q494.077 335.463 491.039 344.659 Q488.042 353.854 481.965 363.374 L475.484 363.374 Q480.872 354.098 483.505 344.942 Q486.178 335.747 486.178 326.389 Q486.178 317.032 483.505 307.917 Q480.872 298.803 475.484 289.486 Z\" fill=\"#ff0000\" fill-rule=\"nonzero\" fill-opacity=\"1\" /><path clip-path=\"url(#clip510)\" d=\"M754.246 641.653 L782.805 641.653 L782.805 648.539 L744.403 648.539 L744.403 641.653 Q749.061 636.832 757.082 628.73 Q765.143 620.588 767.209 618.239 Q771.138 613.823 772.678 610.785 Q774.258 607.706 774.258 604.749 Q774.258 599.929 770.855 596.89 Q767.493 593.852 762.064 593.852 Q758.216 593.852 753.922 595.189 Q749.669 596.526 744.808 599.24 L744.808 590.976 Q749.75 588.991 754.044 587.978 Q758.338 586.966 761.902 586.966 Q771.301 586.966 776.891 591.665 Q782.481 596.364 782.481 604.223 Q782.481 607.949 781.063 611.312 Q779.686 614.633 776 619.17 Q774.987 620.345 769.559 625.976 Q764.13 631.566 754.246 641.653 Z\" fill=\"#ff0000\" fill-rule=\"nonzero\" fill-opacity=\"1\" /><path clip-path=\"url(#clip510)\" d=\"M677.806 712.49 Q672.377 721.807 669.744 730.921 Q667.111 740.036 667.111 749.393 Q667.111 758.751 669.744 767.946 Q672.418 777.101 677.806 786.378 L671.324 786.378 Q665.248 776.858 662.21 767.663 Q659.212 758.467 659.212 749.393 Q659.212 740.36 662.21 731.205 Q665.207 722.05 671.324 712.49 L677.806 712.49 Z\" fill=\"#ff0000\" fill-rule=\"nonzero\" fill-opacity=\"1\" /><path clip-path=\"url(#clip510)\" d=\"M700.369 768.554 L728.928 768.554 L728.928 775.441 L690.525 775.441 L690.525 768.554 Q695.184 763.733 703.205 755.632 Q711.266 747.489 713.332 745.14 Q717.261 740.724 718.801 737.686 Q720.381 734.607 720.381 731.65 Q720.381 726.83 716.978 723.792 Q713.616 720.753 708.187 720.753 Q704.339 720.753 700.045 722.09 Q695.792 723.427 690.931 726.141 L690.931 717.877 Q695.873 715.892 700.167 714.88 Q704.461 713.867 708.025 713.867 Q717.423 713.867 723.014 718.566 Q728.604 723.265 728.604 731.124 Q728.604 734.851 727.186 738.213 Q725.809 741.535 722.123 746.072 Q721.11 747.246 715.682 752.877 Q710.253 758.467 700.369 768.554 Z\" fill=\"#ff0000\" fill-rule=\"nonzero\" fill-opacity=\"1\" /><path clip-path=\"url(#clip510)\" d=\"M746.955 765.151 L755.502 765.151 L755.502 772.119 L748.859 785.082 L743.633 785.082 L746.955 772.119 L746.955 765.151 Z\" fill=\"#ff0000\" fill-rule=\"nonzero\" fill-opacity=\"1\" /><path clip-path=\"url(#clip510)\" d=\"M798.928 714.961 L831.051 714.961 L831.051 721.847 L806.422 721.847 L806.422 736.673 Q808.204 736.066 809.987 735.782 Q811.769 735.458 813.551 735.458 Q823.679 735.458 829.593 741.008 Q835.507 746.558 835.507 756.037 Q835.507 765.799 829.431 771.228 Q823.355 776.615 812.296 776.615 Q808.488 776.615 804.518 775.967 Q800.589 775.319 796.376 774.023 L796.376 765.799 Q800.021 767.784 803.91 768.757 Q807.799 769.729 812.134 769.729 Q819.142 769.729 823.233 766.042 Q827.325 762.356 827.325 756.037 Q827.325 749.717 823.233 746.031 Q819.142 742.345 812.134 742.345 Q808.852 742.345 805.571 743.074 Q802.33 743.803 798.928 745.342 L798.928 714.961 Z\" fill=\"#ff0000\" fill-rule=\"nonzero\" fill-opacity=\"1\" /><path clip-path=\"url(#clip510)\" d=\"M849.402 712.49 L855.883 712.49 Q861.96 722.05 864.957 731.205 Q867.996 740.36 867.996 749.393 Q867.996 758.467 864.957 767.663 Q861.96 776.858 855.883 786.378 L849.402 786.378 Q854.79 777.101 857.423 767.946 Q860.096 758.751 860.096 749.393 Q860.096 740.036 857.423 730.921 Q854.79 721.807 849.402 712.49 Z\" fill=\"#ff0000\" fill-rule=\"nonzero\" fill-opacity=\"1\" /><path clip-path=\"url(#clip510)\" d=\"M957.996 615.93 Q963.87 617.185 967.151 621.155 Q970.473 625.125 970.473 630.958 Q970.473 639.911 964.316 644.813 Q958.158 649.714 946.816 649.714 Q943.008 649.714 938.957 648.944 Q934.947 648.215 930.653 646.717 L930.653 638.817 Q934.055 640.802 938.106 641.815 Q942.157 642.828 946.573 642.828 Q954.269 642.828 958.28 639.789 Q962.331 636.751 962.331 630.958 Q962.331 625.611 958.563 622.614 Q954.837 619.575 948.153 619.575 L941.104 619.575 L941.104 612.851 L948.477 612.851 Q954.513 612.851 957.713 610.461 Q960.913 608.03 960.913 603.493 Q960.913 598.835 957.591 596.364 Q954.31 593.852 948.153 593.852 Q944.79 593.852 940.942 594.581 Q937.094 595.311 932.476 596.85 L932.476 589.558 Q937.134 588.262 941.185 587.614 Q945.276 586.966 948.882 586.966 Q958.199 586.966 963.627 591.219 Q969.055 595.432 969.055 602.643 Q969.055 607.666 966.179 611.15 Q963.303 614.593 957.996 615.93 Z\" fill=\"#ff0000\" fill-rule=\"nonzero\" fill-opacity=\"1\" /><path clip-path=\"url(#clip510)\" d=\"M864.765 712.49 Q859.337 721.807 856.703 730.921 Q854.07 740.036 854.07 749.393 Q854.07 758.751 856.703 767.946 Q859.377 777.101 864.765 786.378 L858.283 786.378 Q852.207 776.858 849.169 767.663 Q846.171 758.467 846.171 749.393 Q846.171 740.36 849.169 731.205 Q852.166 722.05 858.283 712.49 L864.765 712.49 Z\" fill=\"#ff0000\" fill-rule=\"nonzero\" fill-opacity=\"1\" /><path clip-path=\"url(#clip510)\" d=\"M905.071 742.831 Q910.945 744.087 914.226 748.056 Q917.548 752.026 917.548 757.86 Q917.548 766.812 911.391 771.714 Q905.233 776.615 893.891 776.615 Q890.083 776.615 886.032 775.846 Q882.022 775.117 877.728 773.618 L877.728 765.718 Q881.13 767.703 885.181 768.716 Q889.232 769.729 893.648 769.729 Q901.344 769.729 905.355 766.691 Q909.406 763.652 909.406 757.86 Q909.406 752.512 905.638 749.515 Q901.912 746.477 895.228 746.477 L888.179 746.477 L888.179 739.752 L895.552 739.752 Q901.587 739.752 904.788 737.362 Q907.988 734.932 907.988 730.395 Q907.988 725.736 904.666 723.265 Q901.385 720.753 895.228 720.753 Q891.865 720.753 888.017 721.483 Q884.169 722.212 879.551 723.751 L879.551 716.459 Q884.209 715.163 888.26 714.515 Q892.351 713.867 895.957 713.867 Q905.274 713.867 910.702 718.12 Q916.13 722.333 916.13 729.544 Q916.13 734.567 913.254 738.051 Q910.378 741.494 905.071 742.831 Z\" fill=\"#ff0000\" fill-rule=\"nonzero\" fill-opacity=\"1\" /><path clip-path=\"url(#clip510)\" d=\"M933.914 765.151 L942.461 765.151 L942.461 772.119 L935.818 785.082 L930.592 785.082 L933.914 772.119 L933.914 765.151 Z\" fill=\"#ff0000\" fill-rule=\"nonzero\" fill-opacity=\"1\" /><path clip-path=\"url(#clip510)\" d=\"M985.887 714.961 L1018.01 714.961 L1018.01 721.847 L993.381 721.847 L993.381 736.673 Q995.163 736.066 996.946 735.782 Q998.728 735.458 1000.51 735.458 Q1010.64 735.458 1016.55 741.008 Q1022.47 746.558 1022.47 756.037 Q1022.47 765.799 1016.39 771.228 Q1010.31 776.615 999.255 776.615 Q995.447 776.615 991.477 775.967 Q987.548 775.319 983.335 774.023 L983.335 765.799 Q986.98 767.784 990.869 768.757 Q994.758 769.729 999.093 769.729 Q1006.1 769.729 1010.19 766.042 Q1014.28 762.356 1014.28 756.037 Q1014.28 749.717 1010.19 746.031 Q1006.1 742.345 999.093 742.345 Q995.811 742.345 992.53 743.074 Q989.29 743.803 985.887 745.342 L985.887 714.961 Z\" fill=\"#ff0000\" fill-rule=\"nonzero\" fill-opacity=\"1\" /><path clip-path=\"url(#clip510)\" d=\"M1036.36 712.49 L1042.84 712.49 Q1048.92 722.05 1051.92 731.205 Q1054.95 740.36 1054.95 749.393 Q1054.95 758.467 1051.92 767.663 Q1048.92 776.858 1042.84 786.378 L1036.36 786.378 Q1041.75 777.101 1044.38 767.946 Q1047.06 758.751 1047.06 749.393 Q1047.06 740.036 1044.38 730.921 Q1041.75 721.807 1036.36 712.49 Z\" fill=\"#ff0000\" fill-rule=\"nonzero\" fill-opacity=\"1\" /><path clip-path=\"url(#clip510)\" d=\"M559.813 1381.91 L573.181 1381.91 L573.181 1335.77 L558.638 1338.69 L558.638 1331.23 L573.1 1328.32 L581.283 1328.32 L581.283 1381.91 L594.651 1381.91 L594.651 1388.8 L559.813 1388.8 L559.813 1381.91 Z\" fill=\"#000000\" fill-rule=\"nonzero\" fill-opacity=\"1\" /><path clip-path=\"url(#clip510)\" d=\"M451.269 1452.75 Q445.841 1462.06 443.208 1471.18 Q440.575 1480.29 440.575 1489.65 Q440.575 1499.01 443.208 1508.2 Q445.882 1517.36 451.269 1526.63 L444.788 1526.63 Q438.711 1517.12 435.673 1507.92 Q432.676 1498.72 432.676 1489.65 Q432.676 1480.62 435.673 1471.46 Q438.671 1462.31 444.788 1452.75 L451.269 1452.75 Z\" fill=\"#000000\" fill-rule=\"nonzero\" fill-opacity=\"1\" /><path clip-path=\"url(#clip510)\" d=\"M468.202 1508.81 L481.57 1508.81 L481.57 1462.67 L467.027 1465.59 L467.027 1458.13 L481.489 1455.22 L489.672 1455.22 L489.672 1508.81 L503.04 1508.81 L503.04 1515.7 L468.202 1515.7 L468.202 1508.81 Z\" fill=\"#000000\" fill-rule=\"nonzero\" fill-opacity=\"1\" /><path clip-path=\"url(#clip510)\" d=\"M520.418 1505.41 L528.966 1505.41 L528.966 1512.38 L522.322 1525.34 L517.096 1525.34 L520.418 1512.38 L520.418 1505.41 Z\" fill=\"#000000\" fill-rule=\"nonzero\" fill-opacity=\"1\" /><path clip-path=\"url(#clip510)\" d=\"M573.728 1508.81 L587.096 1508.81 L587.096 1462.67 L572.553 1465.59 L572.553 1458.13 L587.015 1455.22 L595.198 1455.22 L595.198 1508.81 L608.566 1508.81 L608.566 1515.7 L573.728 1515.7 L573.728 1508.81 Z\" fill=\"#000000\" fill-rule=\"nonzero\" fill-opacity=\"1\" /><path clip-path=\"url(#clip510)\" d=\"M625.094 1505.41 L633.641 1505.41 L633.641 1515.7 L625.094 1515.7 L625.094 1505.41 Z\" fill=\"#000000\" fill-rule=\"nonzero\" fill-opacity=\"1\" /><path clip-path=\"url(#clip510)\" d=\"M651.546 1455.22 L683.67 1455.22 L683.67 1462.1 L659.04 1462.1 L659.04 1476.93 Q660.823 1476.32 662.605 1476.04 Q664.387 1475.72 666.17 1475.72 Q676.297 1475.72 682.211 1481.26 Q688.126 1486.81 688.126 1496.29 Q688.126 1506.06 682.049 1511.48 Q675.973 1516.87 664.914 1516.87 Q661.106 1516.87 657.136 1516.22 Q653.207 1515.58 648.994 1514.28 L648.994 1506.06 Q652.64 1508.04 656.529 1509.01 Q660.417 1509.99 664.752 1509.99 Q671.76 1509.99 675.851 1506.3 Q679.943 1502.61 679.943 1496.29 Q679.943 1489.97 675.851 1486.29 Q671.76 1482.6 664.752 1482.6 Q661.471 1482.6 658.189 1483.33 Q654.949 1484.06 651.546 1485.6 L651.546 1455.22 Z\" fill=\"#000000\" fill-rule=\"nonzero\" fill-opacity=\"1\" /><path clip-path=\"url(#clip510)\" d=\"M702.02 1452.75 L708.502 1452.75 Q714.578 1462.31 717.576 1471.46 Q720.614 1480.62 720.614 1489.65 Q720.614 1498.72 717.576 1507.92 Q714.578 1517.12 708.502 1526.63 L702.02 1526.63 Q707.408 1517.36 710.041 1508.2 Q712.715 1499.01 712.715 1489.65 Q712.715 1480.29 710.041 1471.18 Q707.408 1462.06 702.02 1452.75 Z\" fill=\"#000000\" fill-rule=\"nonzero\" fill-opacity=\"1\" /><path clip-path=\"url(#clip510)\" d=\"M941.205 218.649 L969.764 218.649 L969.764 225.535 L931.362 225.535 L931.362 218.649 Q936.02 213.828 944.041 205.727 Q952.102 197.584 954.168 195.235 Q958.098 190.819 959.637 187.781 Q961.217 184.702 961.217 181.745 Q961.217 176.925 957.814 173.886 Q954.452 170.848 949.024 170.848 Q945.175 170.848 940.881 172.185 Q936.628 173.522 931.767 176.236 L931.767 167.972 Q936.709 165.987 941.003 164.974 Q945.297 163.962 948.861 163.962 Q958.26 163.962 963.85 168.661 Q969.44 173.36 969.44 181.219 Q969.44 184.945 968.022 188.308 Q966.645 191.629 962.959 196.166 Q961.946 197.341 956.518 202.972 Q951.089 208.562 941.205 218.649 Z\" fill=\"#000000\" fill-rule=\"nonzero\" fill-opacity=\"1\" /><path clip-path=\"url(#clip510)\" d=\"M864.765 289.486 Q859.337 298.803 856.703 307.917 Q854.07 317.032 854.07 326.389 Q854.07 335.747 856.703 344.942 Q859.377 354.098 864.765 363.374 L858.283 363.374 Q852.207 353.854 849.169 344.659 Q846.171 335.463 846.171 326.389 Q846.171 317.356 849.169 308.201 Q852.166 299.046 858.283 289.486 L864.765 289.486 Z\" fill=\"#000000\" fill-rule=\"nonzero\" fill-opacity=\"1\" /><path clip-path=\"url(#clip510)\" d=\"M905.071 319.827 Q910.945 321.083 914.226 325.053 Q917.548 329.022 917.548 334.856 Q917.548 343.808 911.391 348.71 Q905.233 353.611 893.891 353.611 Q890.083 353.611 886.032 352.842 Q882.022 352.113 877.728 350.614 L877.728 342.714 Q881.13 344.699 885.181 345.712 Q889.232 346.725 893.648 346.725 Q901.344 346.725 905.355 343.687 Q909.406 340.649 909.406 334.856 Q909.406 329.509 905.638 326.511 Q901.912 323.473 895.228 323.473 L888.179 323.473 L888.179 316.748 L895.552 316.748 Q901.587 316.748 904.788 314.358 Q907.988 311.928 907.988 307.391 Q907.988 302.732 904.666 300.261 Q901.385 297.749 895.228 297.749 Q891.865 297.749 888.017 298.479 Q884.169 299.208 879.551 300.747 L879.551 293.455 Q884.209 292.159 888.26 291.511 Q892.351 290.863 895.957 290.863 Q905.274 290.863 910.702 295.116 Q916.13 299.329 916.13 306.54 Q916.13 311.563 913.254 315.047 Q910.378 318.49 905.071 319.827 Z\" fill=\"#000000\" fill-rule=\"nonzero\" fill-opacity=\"1\" /><path clip-path=\"url(#clip510)\" d=\"M933.914 342.147 L942.461 342.147 L942.461 349.115 L935.818 362.078 L930.592 362.078 L933.914 349.115 L933.914 342.147 Z\" fill=\"#000000\" fill-rule=\"nonzero\" fill-opacity=\"1\" /><path clip-path=\"url(#clip510)\" d=\"M983.74 291.957 L1022.63 291.957 L1022.63 295.44 L1000.67 352.437 L992.125 352.437 L1012.78 298.843 L983.74 298.843 L983.74 291.957 Z\" fill=\"#000000\" fill-rule=\"nonzero\" fill-opacity=\"1\" /><path clip-path=\"url(#clip510)\" d=\"M1036.36 289.486 L1042.84 289.486 Q1048.92 299.046 1051.92 308.201 Q1054.95 317.356 1054.95 326.389 Q1054.95 335.463 1051.92 344.659 Q1048.92 353.854 1042.84 363.374 L1036.36 363.374 Q1041.75 354.098 1044.38 344.942 Q1047.06 335.747 1047.06 326.389 Q1047.06 317.032 1044.38 307.917 Q1041.75 298.803 1036.36 289.486 Z\" fill=\"#000000\" fill-rule=\"nonzero\" fill-opacity=\"1\" /><path clip-path=\"url(#clip510)\" d=\"M1331.91 1038.93 Q1337.79 1040.19 1341.07 1044.16 Q1344.39 1048.13 1344.39 1053.96 Q1344.39 1062.91 1338.23 1067.82 Q1332.08 1072.72 1320.73 1072.72 Q1316.93 1072.72 1312.88 1071.95 Q1308.86 1071.22 1304.57 1069.72 L1304.57 1061.82 Q1307.97 1063.81 1312.02 1064.82 Q1316.08 1065.83 1320.49 1065.83 Q1328.19 1065.83 1332.2 1062.79 Q1336.25 1059.76 1336.25 1053.96 Q1336.25 1048.62 1332.48 1045.62 Q1328.75 1042.58 1322.07 1042.58 L1315.02 1042.58 L1315.02 1035.85 L1322.39 1035.85 Q1328.43 1035.85 1331.63 1033.46 Q1334.83 1031.03 1334.83 1026.5 Q1334.83 1021.84 1331.51 1019.37 Q1328.23 1016.86 1322.07 1016.86 Q1318.71 1016.86 1314.86 1017.59 Q1311.01 1018.31 1306.39 1019.85 L1306.39 1012.56 Q1311.05 1011.27 1315.1 1010.62 Q1319.19 1009.97 1322.8 1009.97 Q1332.12 1009.97 1337.55 1014.22 Q1342.97 1018.44 1342.97 1025.65 Q1342.97 1030.67 1340.1 1034.15 Q1337.22 1037.6 1331.91 1038.93 Z\" fill=\"#000000\" fill-rule=\"nonzero\" fill-opacity=\"1\" /><path clip-path=\"url(#clip510)\" d=\"M1238.68 1135.49 Q1233.25 1144.81 1230.62 1153.93 Q1227.99 1163.04 1227.99 1172.4 Q1227.99 1181.75 1230.62 1190.95 Q1233.3 1200.11 1238.68 1209.38 L1232.2 1209.38 Q1226.13 1199.86 1223.09 1190.67 Q1220.09 1181.47 1220.09 1172.4 Q1220.09 1163.36 1223.09 1154.21 Q1226.08 1145.05 1232.2 1135.49 L1238.68 1135.49 Z\" fill=\"#000000\" fill-rule=\"nonzero\" fill-opacity=\"1\" /><path clip-path=\"url(#clip510)\" d=\"M1254.28 1137.96 L1286.4 1137.96 L1286.4 1144.85 L1261.77 1144.85 L1261.77 1159.68 Q1263.56 1159.07 1265.34 1158.79 Q1267.12 1158.46 1268.9 1158.46 Q1279.03 1158.46 1284.94 1164.01 Q1290.86 1169.56 1290.86 1179.04 Q1290.86 1188.8 1284.78 1194.23 Q1278.71 1199.62 1267.65 1199.62 Q1263.84 1199.62 1259.87 1198.97 Q1255.94 1198.32 1251.73 1197.03 L1251.73 1188.8 Q1255.37 1190.79 1259.26 1191.76 Q1263.15 1192.73 1267.48 1192.73 Q1274.49 1192.73 1278.58 1189.05 Q1282.68 1185.36 1282.68 1179.04 Q1282.68 1172.72 1278.58 1169.03 Q1274.49 1165.35 1267.48 1165.35 Q1264.2 1165.35 1260.92 1166.08 Q1257.68 1166.81 1254.28 1168.35 L1254.28 1137.96 Z\" fill=\"#000000\" fill-rule=\"nonzero\" fill-opacity=\"1\" /><path clip-path=\"url(#clip510)\" d=\"M1307.83 1188.16 L1316.38 1188.16 L1316.38 1195.12 L1309.74 1208.09 L1304.51 1208.09 L1307.83 1195.12 L1307.83 1188.16 Z\" fill=\"#000000\" fill-rule=\"nonzero\" fill-opacity=\"1\" /><path clip-path=\"url(#clip510)\" d=\"M1384.52 1165.83 Q1390.39 1167.09 1393.67 1171.06 Q1396.99 1175.03 1396.99 1180.86 Q1396.99 1189.82 1390.83 1194.72 Q1384.68 1199.62 1373.33 1199.62 Q1369.53 1199.62 1365.48 1198.85 Q1361.47 1198.12 1357.17 1196.62 L1357.17 1188.72 Q1360.57 1190.71 1364.63 1191.72 Q1368.68 1192.73 1373.09 1192.73 Q1380.79 1192.73 1384.8 1189.69 Q1388.85 1186.66 1388.85 1180.86 Q1388.85 1175.52 1385.08 1172.52 Q1381.36 1169.48 1374.67 1169.48 L1367.62 1169.48 L1367.62 1162.76 L1375 1162.76 Q1381.03 1162.76 1384.23 1160.37 Q1387.43 1157.94 1387.43 1153.4 Q1387.43 1148.74 1384.11 1146.27 Q1380.83 1143.76 1374.67 1143.76 Q1371.31 1143.76 1367.46 1144.49 Q1363.61 1145.22 1358.99 1146.75 L1358.99 1139.46 Q1363.65 1138.17 1367.7 1137.52 Q1371.8 1136.87 1375.4 1136.87 Q1384.72 1136.87 1390.15 1141.12 Q1395.57 1145.34 1395.57 1152.55 Q1395.57 1157.57 1392.7 1161.05 Q1389.82 1164.5 1384.52 1165.83 Z\" fill=\"#000000\" fill-rule=\"nonzero\" fill-opacity=\"1\" /><path clip-path=\"url(#clip510)\" d=\"M1410.28 1135.49 L1416.76 1135.49 Q1422.84 1145.05 1425.83 1154.21 Q1428.87 1163.36 1428.87 1172.4 Q1428.87 1181.47 1425.83 1190.67 Q1422.84 1199.86 1416.76 1209.38 L1410.28 1209.38 Q1415.67 1200.11 1418.3 1190.95 Q1420.97 1181.75 1420.97 1172.4 Q1420.97 1163.04 1418.3 1153.93 Q1415.67 1144.81 1410.28 1135.49 Z\" fill=\"#000000\" fill-rule=\"nonzero\" fill-opacity=\"1\" /><path clip-path=\"url(#clip510)\" d=\"M1797.14 383.687 L1776.49 415.973 L1797.14 415.973 L1797.14 383.687 M1795 376.557 L1805.29 376.557 L1805.29 415.973 L1813.92 415.973 L1813.92 422.778 L1805.29 422.778 L1805.29 437.037 L1797.14 437.037 L1797.14 422.778 L1769.84 422.778 L1769.84 414.879 L1795 376.557 Z\" fill=\"#000000\" fill-rule=\"nonzero\" fill-opacity=\"1\" /><path clip-path=\"url(#clip510)\" d=\"M1666.5 500.988 Q1661.07 510.305 1658.44 519.419 Q1655.81 528.534 1655.81 537.891 Q1655.81 547.249 1658.44 556.444 Q1661.12 565.599 1666.5 574.876 L1660.02 574.876 Q1653.95 565.356 1650.91 556.161 Q1647.91 546.965 1647.91 537.891 Q1647.91 528.858 1650.91 519.703 Q1653.9 510.548 1660.02 500.988 L1666.5 500.988 Z\" fill=\"#000000\" fill-rule=\"nonzero\" fill-opacity=\"1\" /><path clip-path=\"url(#clip510)\" d=\"M1679.95 503.459 L1718.84 503.459 L1718.84 506.942 L1696.88 563.939 L1688.34 563.939 L1709 510.345 L1679.95 510.345 L1679.95 503.459 Z\" fill=\"#000000\" fill-rule=\"nonzero\" fill-opacity=\"1\" /><path clip-path=\"url(#clip510)\" d=\"M1734.8 553.649 L1743.35 553.649 L1743.35 563.939 L1734.8 563.939 L1734.8 553.649 Z\" fill=\"#000000\" fill-rule=\"nonzero\" fill-opacity=\"1\" /><path clip-path=\"url(#clip510)\" d=\"M1761.25 503.459 L1793.38 503.459 L1793.38 510.345 L1768.75 510.345 L1768.75 525.171 Q1770.53 524.564 1772.31 524.28 Q1774.1 523.956 1775.88 523.956 Q1786 523.956 1791.92 529.506 Q1797.83 535.056 1797.83 544.535 Q1797.83 554.297 1791.76 559.726 Q1785.68 565.113 1774.62 565.113 Q1770.81 565.113 1766.84 564.465 Q1762.91 563.817 1758.7 562.521 L1758.7 554.297 Q1762.35 556.282 1766.24 557.255 Q1770.13 558.227 1774.46 558.227 Q1781.47 558.227 1785.56 554.541 Q1789.65 550.854 1789.65 544.535 Q1789.65 538.215 1785.56 534.529 Q1781.47 530.843 1774.46 530.843 Q1771.18 530.843 1767.9 531.572 Q1764.66 532.301 1761.25 533.84 L1761.25 503.459 Z\" fill=\"#000000\" fill-rule=\"nonzero\" fill-opacity=\"1\" /><path clip-path=\"url(#clip510)\" d=\"M1814.81 553.649 L1823.35 553.649 L1823.35 560.617 L1816.71 573.58 L1811.49 573.58 L1814.81 560.617 L1814.81 553.649 Z\" fill=\"#000000\" fill-rule=\"nonzero\" fill-opacity=\"1\" /><path clip-path=\"url(#clip510)\" d=\"M1885.21 530.438 Q1879.7 530.438 1876.46 534.205 Q1873.26 537.972 1873.26 544.535 Q1873.26 551.057 1876.46 554.865 Q1879.7 558.632 1885.21 558.632 Q1890.72 558.632 1893.92 554.865 Q1897.16 551.057 1897.16 544.535 Q1897.16 537.972 1893.92 534.205 Q1890.72 530.438 1885.21 530.438 M1901.46 504.795 L1901.46 512.249 Q1898.38 510.791 1895.22 510.021 Q1892.1 509.251 1889.02 509.251 Q1880.92 509.251 1876.62 514.72 Q1872.37 520.189 1871.76 531.248 Q1874.15 527.724 1877.76 525.86 Q1881.36 523.956 1885.7 523.956 Q1894.81 523.956 1900.08 529.506 Q1905.39 535.015 1905.39 544.535 Q1905.39 553.852 1899.88 559.483 Q1894.37 565.113 1885.21 565.113 Q1874.72 565.113 1869.17 557.093 Q1863.62 549.031 1863.62 533.759 Q1863.62 519.419 1870.43 510.912 Q1877.23 502.365 1888.7 502.365 Q1891.77 502.365 1894.89 502.973 Q1898.05 503.58 1901.46 504.795 Z\" fill=\"#000000\" fill-rule=\"nonzero\" fill-opacity=\"1\" /><path clip-path=\"url(#clip510)\" d=\"M1917.25 500.988 L1923.74 500.988 Q1929.81 510.548 1932.81 519.703 Q1935.85 528.858 1935.85 537.891 Q1935.85 546.965 1932.81 556.161 Q1929.81 565.356 1923.74 574.876 L1917.25 574.876 Q1922.64 565.599 1925.27 556.444 Q1927.95 547.249 1927.95 537.891 Q1927.95 528.534 1925.27 519.419 Q1922.64 510.305 1917.25 500.988 Z\" fill=\"#000000\" fill-rule=\"nonzero\" fill-opacity=\"1\" /><path clip-path=\"url(#clip510)\" d=\"M2242.26 588.059 L2274.39 588.059 L2274.39 594.946 L2249.76 594.946 L2249.76 609.772 Q2251.54 609.165 2253.32 608.881 Q2255.1 608.557 2256.89 608.557 Q2267.01 608.557 2272.93 614.107 Q2278.84 619.656 2278.84 629.136 Q2278.84 638.898 2272.77 644.326 Q2266.69 649.714 2255.63 649.714 Q2251.82 649.714 2247.85 649.066 Q2243.92 648.418 2239.71 647.122 L2239.71 638.898 Q2243.36 640.883 2247.25 641.855 Q2251.13 642.828 2255.47 642.828 Q2262.48 642.828 2266.57 639.141 Q2270.66 635.455 2270.66 629.136 Q2270.66 622.816 2266.57 619.13 Q2262.48 615.444 2255.47 615.444 Q2252.19 615.444 2248.91 616.173 Q2245.67 616.902 2242.26 618.441 L2242.26 588.059 Z\" fill=\"#000000\" fill-rule=\"nonzero\" fill-opacity=\"1\" /><path clip-path=\"url(#clip510)\" d=\"M2147.09 712.49 Q2141.66 721.807 2139.03 730.921 Q2136.39 740.036 2136.39 749.393 Q2136.39 758.751 2139.03 767.946 Q2141.7 777.101 2147.09 786.378 L2140.61 786.378 Q2134.53 776.858 2131.49 767.663 Q2128.49 758.467 2128.49 749.393 Q2128.49 740.36 2131.49 731.205 Q2134.49 722.05 2140.61 712.49 L2147.09 712.49 Z\" fill=\"#000000\" fill-rule=\"nonzero\" fill-opacity=\"1\" /><path clip-path=\"url(#clip510)\" d=\"M2164.02 768.554 L2177.39 768.554 L2177.39 722.414 L2162.84 725.331 L2162.84 717.877 L2177.31 714.961 L2185.49 714.961 L2185.49 768.554 L2198.86 768.554 L2198.86 775.441 L2164.02 775.441 L2164.02 768.554 Z\" fill=\"#000000\" fill-rule=\"nonzero\" fill-opacity=\"1\" /><path clip-path=\"url(#clip510)\" d=\"M2232.88 720.348 Q2226.57 720.348 2223.37 726.587 Q2220.21 732.785 2220.21 745.261 Q2220.21 757.698 2223.37 763.936 Q2226.57 770.134 2232.88 770.134 Q2239.24 770.134 2242.4 763.936 Q2245.6 757.698 2245.6 745.261 Q2245.6 732.785 2242.4 726.587 Q2239.24 720.348 2232.88 720.348 M2232.88 713.867 Q2243.05 713.867 2248.4 721.928 Q2253.79 729.949 2253.79 745.261 Q2253.79 760.533 2248.4 768.595 Q2243.05 776.615 2232.88 776.615 Q2222.72 776.615 2217.33 768.595 Q2211.98 760.533 2211.98 745.261 Q2211.98 729.949 2217.33 721.928 Q2222.72 713.867 2232.88 713.867 Z\" fill=\"#000000\" fill-rule=\"nonzero\" fill-opacity=\"1\" /><path clip-path=\"url(#clip510)\" d=\"M2269.02 765.151 L2277.57 765.151 L2277.57 772.119 L2270.92 785.082 L2265.7 785.082 L2269.02 772.119 L2269.02 765.151 Z\" fill=\"#000000\" fill-rule=\"nonzero\" fill-opacity=\"1\" /><path clip-path=\"url(#clip510)\" d=\"M2320.99 714.961 L2353.12 714.961 L2353.12 721.847 L2328.49 721.847 L2328.49 736.673 Q2330.27 736.066 2332.05 735.782 Q2333.83 735.458 2335.62 735.458 Q2345.74 735.458 2351.66 741.008 Q2357.57 746.558 2357.57 756.037 Q2357.57 765.799 2351.5 771.228 Q2345.42 776.615 2334.36 776.615 Q2330.55 776.615 2326.58 775.967 Q2322.65 775.319 2318.44 774.023 L2318.44 765.799 Q2322.09 767.784 2325.97 768.757 Q2329.86 769.729 2334.2 769.729 Q2341.21 769.729 2345.3 766.042 Q2349.39 762.356 2349.39 756.037 Q2349.39 749.717 2345.3 746.031 Q2341.21 742.345 2334.2 742.345 Q2330.92 742.345 2327.64 743.074 Q2324.39 743.803 2320.99 745.342 L2320.99 714.961 Z\" fill=\"#000000\" fill-rule=\"nonzero\" fill-opacity=\"1\" /><path clip-path=\"url(#clip510)\" d=\"M2371.47 712.49 L2377.95 712.49 Q2384.02 722.05 2387.02 731.205 Q2390.06 740.36 2390.06 749.393 Q2390.06 758.467 2387.02 767.663 Q2384.02 776.858 2377.95 786.378 L2371.47 786.378 Q2376.85 777.101 2379.49 767.946 Q2382.16 758.751 2382.16 749.393 Q2382.16 740.036 2379.49 730.921 Q2376.85 721.807 2371.47 712.49 Z\" fill=\"#000000\" fill-rule=\"nonzero\" fill-opacity=\"1\" /><path clip-path=\"url(#clip510)\" d=\"M1231 8.36409 L1241.63 8.36409 L1257.98 74.0929 L1274.28 8.36409 L1286.11 8.36409 L1302.46 74.0929 L1318.76 8.36409 L1329.44 8.36409 L1309.91 86.1241 L1296.68 86.1241 L1280.27 18.6245 L1263.71 86.1241 L1250.48 86.1241 L1231 8.36409 Z\" fill=\"#0000ff\" fill-rule=\"nonzero\" fill-opacity=\"1\" /><path clip-path=\"url(#clip510)\" d=\"M1340.64 27.7911 L1350.22 27.7911 L1350.22 86.1241 L1340.64 86.1241 L1340.64 27.7911 M1340.64 5.08286 L1350.22 5.08286 L1350.22 17.2182 L1340.64 17.2182 L1340.64 5.08286 Z\" fill=\"#0000ff\" fill-rule=\"nonzero\" fill-opacity=\"1\" /><path clip-path=\"url(#clip510)\" d=\"M1418.76 50.9159 L1418.76 86.1241 L1409.18 86.1241 L1409.18 51.2284 Q1409.18 42.9472 1405.95 38.8327 Q1402.72 34.7181 1396.26 34.7181 Q1388.5 34.7181 1384.02 39.666 Q1379.54 44.6139 1379.54 53.1555 L1379.54 86.1241 L1369.91 86.1241 L1369.91 27.7911 L1379.54 27.7911 L1379.54 36.8535 Q1382.98 31.5931 1387.62 28.989 Q1392.3 26.3848 1398.4 26.3848 Q1408.45 26.3848 1413.6 32.6348 Q1418.76 38.8327 1418.76 50.9159 Z\" fill=\"#0000ff\" fill-rule=\"nonzero\" fill-opacity=\"1\" /><path clip-path=\"url(#clip510)\" d=\"M1476.26 36.6452 L1476.26 5.08286 L1485.84 5.08286 L1485.84 86.1241 L1476.26 86.1241 L1476.26 77.3741 Q1473.24 82.5824 1468.6 85.1345 Q1464.02 87.6345 1457.56 87.6345 Q1446.99 87.6345 1440.32 79.197 Q1433.71 70.7596 1433.71 57.0097 Q1433.71 43.2597 1440.32 34.8223 Q1446.99 26.3848 1457.56 26.3848 Q1464.02 26.3848 1468.6 28.9369 Q1473.24 31.4369 1476.26 36.6452 M1443.6 57.0097 Q1443.6 67.5825 1447.93 73.6242 Q1452.3 79.6137 1459.91 79.6137 Q1467.51 79.6137 1471.89 73.6242 Q1476.26 67.5825 1476.26 57.0097 Q1476.26 46.4368 1471.89 40.4473 Q1467.51 34.4056 1459.91 34.4056 Q1452.3 34.4056 1447.93 40.4473 Q1443.6 46.4368 1443.6 57.0097 Z\" fill=\"#0000ff\" fill-rule=\"nonzero\" fill-opacity=\"1\" /></svg>\n```\n:::\n:::\n\n\n:::\n::::\n\n## Modeling Considerations\n\nNeed to know relationship between source emissions ($Q_i$) and receptor exposure.\n\n- Receptors are only affected by upwind sources.\n- Individual plume model gives us concentrations. How to combine?\n\n::: {.fragment .fade-in}\n$$\nC_\\text{total} = \\frac{M_1 + M_2 + M_3}{V} = \\frac{M_1}{V} + \\frac{M_2}{V} + \\frac{M_3}{V} = C_1 + C_2 + C_3\n$$\n:::\n\n## Decision Variables\n\n**What is the key set of decision variables?**\n\n::: {.fragment .fade-in}\nFraction of SO~2~ removed at source $i$: $R_i$.\n\nAlternatively, can reframe as level of emissions: \n$$Q_i = (1-R_i) \\times E_i,$$\nwhere $E_i$ is the emissions level (given in problem).\n:::\n\n## Constraints\n\n**What is our main constraint?**\n\n::: {.fragment .fade-in}\nNeed to ensure compliance with the air quality standard:\n\n$$\\text{Exp}_j \\leq .00015 \\text{g/m}^3$$\n\nThis means that we need to express $\\text{Exp}_j$ as a linear function of the $R_i$.\n:::\n\n## Developing Constraints\n\nWrite $C_i(x,y) = Q_it_i(x,y)$, where the $t_i$ is the transmission factor from the Gaussian dispersion model:\n\n$$t_i(x,y) = \\frac{1}{2\\pi u \\sigma_y \\sigma_z} \\exp\\left(\\frac{-y^2}{2\\sigma_y^2} + \\frac{H^2}{\\sigma_z^2}\\right)$$\n\n\n## Developing Constraints\n\nThis lets us write the exposure constraints as a linear function of $R_i$: \n\nFor a receptor $j$ (with fixed location $(x_j, y_j)$),\n\n$$\n\\begin{align}\n\\text{Exp}_j &= \\sum_i Q_i t_i(x_j, y_j) \\\\\n&= (1-R_i)E_it_i(x_j, y_j) \\leq 0.00015\\ \\text{g/m}^3\n\\end{align}\n$$\n\nWrite $t_{ij} = t_i(x_j, y_j)$.\n\n## Dispersion Spread\n\nHowever, we still need to do this analysis given a particular atmospheric stability class (or can test across all). Let's assume we're in stability class C.\n\n![Dispersion Coefficients](figures/plume-dispersion.png)\n\n::: {.caption}\nSource: <https://courses.washington.edu/cee490/DISPCOEF4WP.htm>\n:::\n\n## Dispersion Spread\n\nUsing the equations:\n\n$$\\begin{align}\n\\sigma_y &= ax^{0.894} \\\\[0.5em]\n\\sigma_z &= cx^d + f,\n\\end{align}$$\n\nwe have $$\\sigma_y = 104x^{0.894}, \\qquad \\sigma_z = 61x^{0.911}.$$\n\n## Calculating Transmission Factors\n\n::: {#66acee82 .cell execution_count=4}\n``` {.julia .cell-code}\n# delta_x, delta_y should be in m\nfunction transmission_factor(Δx, Δy, u, H)\n    if Δx <= 0 # check if source is upwind of receptor\n        tf = 0.0 # ensure this is a Float\n    else\n        σy = 104 * (Δx / 1000)^0.894\n        σz = 61 * (Δx / 1000)^0.911\n        tf_coef = 1/(2 * pi * u * σy * σz)\n        tf = tf_coef * exp((-0.5 * (Δy / σy)^2) + (H / σz)^2)\n    end\n    return tf\nend\n```\n:::\n\n\n## Calculating Transmission Factors\n\nFor example, from Source 1 to Receptor 1:\n\n::: {#232f7f35 .cell execution_count=5}\n``` {.julia .cell-code}\ntransmission_factor(1000, 5500, 1.5, 50)\n```\n\n::: {.cell-output .cell-output-display execution_count=299}\n```\n0.0\n```\n:::\n:::\n\n\nOr from Source 1 to Receptor 2:\n\n::: {#0dca3e50 .cell execution_count=6}\n``` {.julia .cell-code}\ntransmission_factor(3000, 0, 1.5, 50)\n```\n\n::: {.cell-output .cell-output-display execution_count=300}\n```\n2.521069616495523e-6\n```\n:::\n:::\n\n\n## Objective\n\n**What is our objective?**\n\n::: {.fragment .fade-in}\nMinimize cost:\n\n$$\n\\begin{align}\n\\min_{R_i} & \\sum_i RemCost_i \\times (E_i \\times R_i) \\\\[0.5em]\n&= (0.20) (34560) R_1 + (0.45)(172800) R_2 + (0.60)(103680) R_3 \\\\[0.5em]\n&= 6912R_1 + 77760R_2 + 62208R_3\n\\end{align}\n$$\n:::\n\n## Final Problem\n\n$$\n\\begin{align}\n\\min_{R_i} \\quad & \\sum_i RemCost_i \\times (E_i \\times R_i) & \\\\\n\\text{subject to:} & \\\\[0.5em]\n&  \\sum_{i=1}^3 E_i (1-R_i)t_{ij} \\leq 0.00015 & \\forall j \\in 1:5 \\\\[0.5em]\n& R_i \\geq 0 & \\forall i \\in 1:3 \\\\[0.5em]\n& R_i \\leq 1 & \\forall i \\in 1:3 \n\\end{align}\n$$\n\n## Solution\n\n::: {#056008d0 .cell execution_count=7}\n\n::: {.cell-output .cell-output-display execution_count=301}\n| Source | SO2 Emissions (g/m^3) | Removal Percentage (%) |\n|--------|-----------------------|------------------------|\n|      1 |                   400 |                   85.0 |\n|      2 |                  2000 |                  100.0 |\n|      3 |                  1200 |                   75.0 |\n\n:::\n:::\n\n\n**Does this make sense?**\n\n## Untreated Exposure \n\nIn the absence of our treatment plan (exposure in $\\mu$g/m$^3$):\n\n::: {#efb0c0f2 .cell execution_count=8}\n\n::: {.cell-output .cell-output-display execution_count=302}\n| Source | R1  | R2     | R3  | R4    | R5     |\n|--------|-----|--------|-----|-------|--------|\n|      1 | 0.0 | 1008.0 | 0.0 |  51.0 |    5.0 |\n|      2 | 0.0 |    0.0 | 0.0 | 278.0 | 1000.0 |\n|      3 | 0.0 |    0.0 | 0.0 |  58.0 |  603.0 |\n\n:::\n:::\n\n\nNeed to reduce Source 1's emissions to bring Receptor 2's exposure down. What about Sources 2 and 3?\n\n\n## Why This Plan Makes Sense\n\nWe *could* reduce emissions from source 2 by ~85% to comply at receptor 5, but then would also need to reduce source 3's emissions by 100%. \n\nThis plan involves eliminating all of source 2's emissions, but only 75% of source 3's.\n\nSince removal at source 2 (\\$0.45/kg) is cheaper than source 3 (\\$0.60/kg), eliminating all of source 2's is cheaper, at a cost of **$124,416**.\n\n## Treated Exposure\n\n::: {#36e82978 .cell execution_count=9}\n\n::: {.cell-output .cell-output-display execution_count=303}\n| Source | R1  | R2    | R3  | R4   | R5    |\n|--------|-----|-------|-----|------|-------|\n|      1 | 0.0 | 150.0 | 0.0 |  8.0 |   1.0 |\n|      2 | 0.0 |   0.0 | 0.0 |  0.0 |   0.0 |\n|      3 | 0.0 |   0.0 | 0.0 | 14.0 | 149.0 |\n\n:::\n:::\n\n\n# Key Takeaways\n\n## Key Takeaways\n\n- Gaussian plume models can be useful for modeling continuous point source emissions.\n- Can turn multi-source and receptor problems into an LP by linearizing Gaussian dispersion model when locations are fixed.\n\n# Upcoming Schedule\n\n## Next Classes\n\n**Monday**: Plant-level emissions control.\n\n**Wednesday/Friday**: Lake Eutrophication Revisited.\n\n## Assessments\n\n**HW4**: Due next Friday (10/27) at 9pm.\n\n",
    "supporting": [
      "lecture09-3_files"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js\" integrity=\"sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js\" integrity=\"sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==\" crossorigin=\"anonymous\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}